"use client";
import { useRef,useState } from 'react';
import { useLocale,useTranslations } from 'next-intl';
import { ArrowUpRight,ImagePlus,Play,User } from 'lucide-react';
import DetailsDialog from '@/components/ui/DetailsDialog';
import ContentImage from '@/components/hub/ContentImage';
import { communityCopy } from '@/lib/data/community-copy';
import { safeMediaLink,type CommunityEntry } from '@/lib/data/community';
import { CONTENT_IMAGE_UPLOAD_BYTES } from '@/lib/data/content-media';
import { useCommunity } from './CommunityProvider';

export default function CommunityGallery({topic='minecraft'}:{topic?:'minecraft'|'fortnite'}) {
 const locale=useLocale(),c=communityCopy(locale),hub=useTranslations('hub'),store=useTranslations('store'),{entries,available,loading}=useCommunity();
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reference,setReference]=useState(''),lock=useRef(false);
 const [selected,setSelected]=useState<CommunityEntry|null>(null);
 const gallery=entries.filter(e=>e.kind==='gallery'&&e.topic===topic);
 return <><div className="community-gallery-header"><p className="hub-muted">{c.reviewNote}</p><button type="button" className="hub-button" disabled={busy} aria-haspopup="dialog" data-cursor="button" onClick={()=>{setMessage('');setReference('');setOpen(true);}}><ImagePlus size={17} aria-hidden="true"/>{c.submit}</button></div>{gallery.length?<div className="community-grid">{gallery.map(entry=>{
  const video=safeMediaLink(entry.payload.videoUrl);
  return <article key={entry.id} className="community-card community-gallery-card card-glow">{entry.image?<button type="button" className="community-gallery-image-button" onClick={()=>setSelected(entry)} aria-haspopup="dialog" aria-label={store('details')+' — '+entry.title} data-cursor="image"><ContentImage image={entry.image} title={entry.title}/></button>:video?<a href={video} target="_blank" rel="noopener noreferrer" className="community-gallery-video" aria-label={c.mediaLink+' — '+entry.title} data-cursor="link"><Play size={36} aria-hidden="true"/></a>:null}<div className="community-gallery-content"><h3 dir="auto">{entry.title}</h3>{entry.body&&<p dir="auto">{entry.body}</p>}<div className="community-meta"><span><User size={14} aria-hidden="true"/><b dir="auto">{entry.author}</b></span><time dateTime={entry.createdAt}>{new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(entry.createdAt))}</time></div>{video&&<a href={video} target="_blank" rel="noopener noreferrer" className="hub-button" data-cursor="link">{c.mediaLink}<ArrowUpRight size={15} aria-hidden="true"/></a>}</div></article>;
 })}</div>:<p className="community-empty" role="status"><ImagePlus size={20} aria-hidden="true"/>{loading?c.loading:available?c.empty:c.unavailable}</p>}{open&&<DetailsDialog title={c.submit} onClose={()=>setOpen(false)} style={{width:'min(600px,calc(100vw - 24px))'}}><div className="community-dialog-body">{reference?<div role="status"><p>{c.submitted}</p><p className="hub-muted mt-4">{hub('reference')}: <code dir="ltr">{reference}</code></p></div>:<form className="hub-form" onSubmit={async event=>{
  event.preventDefault();if(lock.current)return;const form=new FormData(event.currentTarget),file=form.get('image');
  if(file instanceof File&&file.size>CONTENT_IMAGE_UPLOAD_BYTES){setMessage('imageTooLarge');return;}
  if(!(file instanceof File&&file.size)&&!safeMediaLink(form.get('videoUrl'))){setMessage('imageOrVideo');return;}
  lock.current=true;setBusy(true);setMessage('');form.set('locale',locale);form.set('topic',topic);
  try{const response=await fetch('/api/community/gallery',{method:'POST',body:form}),result=await response.json();if(!response.ok)throw Error(result.error);setReference(result.reference);}
  catch(error){setMessage(error instanceof Error&&error.message==='RATE_LIMIT'?'rateLimit':error instanceof Error&&['IMAGE_FORMAT','IMAGE_SIZE'].includes(error.message)?'imageInvalid':'unavailable');}
  finally{setBusy(false);lock.current=false;}
 }}><label>{c.title}<input name="title" required maxLength={160}/></label><label>{c.author}<input name="author" required maxLength={64}/></label><label>{c.email}<input type="email" name="email" required maxLength={254} autoComplete="email"/></label><label>{c.body}<textarea name="body" maxLength={2000} rows={4}/></label><label>{c.image}<input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif"/><small className="hub-muted">PNG · JPG · WebP · GIF · AVIF · {Math.round(CONTENT_IMAGE_UPLOAD_BYTES/1048576*10)/10} MB</small></label><label>{c.mediaLink}<input type="url" name="videoUrl" dir="ltr" maxLength={1000} placeholder="https://www.youtube.com/…"/></label><label className="hub-honey" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="hub-consent"><input type="checkbox" name="consent" required/>{c.consent}</label><p className="hub-muted">{c.reviewNote}</p>{message&&<p role="alert" className="hub-error">{message==='imageOrVideo'?c.imageOrVideo:hub.has(message)?hub(message):c.unavailable}</p>}<button className="hub-button" disabled={busy} data-cursor="button">{busy?c.loading:c.submit}</button></form>}</div></DetailsDialog>}{selected&&<DetailsDialog title={selected.title} onClose={()=>setSelected(null)} style={{width:"min(820px,calc(100vw - 24px))"}}><div className="community-dialog-body community-gallery-full"><ContentImage image={selected.image} title={selected.title}/><h3 dir="auto">{selected.author}</h3><p dir="auto">{selected.body}</p>{safeMediaLink(selected.payload.videoUrl)&&<a href={safeMediaLink(selected.payload.videoUrl)!} className="hub-button" target="_blank" rel="noopener noreferrer">{c.mediaLink}<ArrowUpRight size={15} aria-hidden="true"/></a>}</div></DetailsDialog>}</>;
}
