"use client";
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {useLocale,useTranslations} from 'next-intl';
import {Gamepad2,Link2,KeyRound,Settings,Copy,Check,LoaderCircle,UserRound} from 'lucide-react';
import AccountIdentityIcon from './AccountIdentityIcon';
import PlayerProfile from '@/components/hub/PlayerProfile';
import {LOCALES,LOCALE_LABELS,LOCALE_COOKIE} from '@/i18n/config';
import AccountLogin from './AccountLogin';
import {useAccount,accountAction} from './AccountProvider';
import {ACCOUNT_PROVIDERS,accountProviderName,minecraftName} from '@/lib/data/account';
export default function AccountCenter() {
 const t=useTranslations('account'),locale=useLocale(),{account,configured,ready,error:loadError,providers,refresh}=useAccount();
 const params=useSearchParams();
 const [tab,setTab]=useState('settings'),[login,setLogin]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[code,setCode]=useState<{code:string;expiresAt:string}|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{const requested=params.get('tab');if(['settings','connections','password','player'].includes(requested??''))queueMicrotask(()=>setTab(requested!));if(params.get('auth')==='error')queueMicrotask(()=>setError(t('errors.AUTH_EXPIRED')));},[params,t]);
 useEffect(()=>{if(!code)return;const interval=setInterval(()=>void refresh(),4000);const timeout=setTimeout(()=>setCode(null),Math.max(0,Date.parse(code.expiresAt)-Date.now()));return()=>{clearInterval(interval);clearTimeout(timeout);};},[code,refresh]);
 useEffect(()=>{if(code&&account?.minecraft && !error)queueMicrotask(()=>{setCode(null);setMessage(t('linkSuccess'));});},[account?.minecraft,code,t,error]);
 const fail=(error:unknown)=>{const key=error instanceof Error?error.message:'UNAVAILABLE';setError(t.has('errors.'+key)?t('errors.'+key):t('errors.UNAVAILABLE'));};
 const run=async(action:string,input:Record<string,unknown>={})=>{setBusy(true);setError('');setMessage('');try{const data=await accountAction(action,input);if(data.url){window.location.assign(data.url);return;}await refresh();setMessage(t(data.message==='EMAIL_SENT'?'emailSent':'saved'));return true;}catch(error){fail(error);return false;}finally{setBusy(false);}};
 if(!ready)return <div className="account-card"><LoaderCircle className="animate-spin" aria-label={t('loading')}/></div>;
 if(!account)return <div className="account-card"><h2>{t('signin')}</h2><p className="account-help">{t('loginIntro')}</p>{(!configured||loadError)&&<p className="account-notice">{t(loadError?'errors.UNAVAILABLE':'errors.CONFIGURATION')}</p>}<button type="button" className="hub-button hub-button-primary mt-6" onClick={()=>setLogin(true)}>{t('signin')}</button>{login&&<AccountLogin onClose={()=>setLogin(false)}/>}</div>;
 return <div className="account-layout">
  <div className="account-card account-profile-heading">{account.avatar?<Image unoptimized src={account.avatar} width={68} height={68} alt=""/>:<UserRound size={48}/>}<div><h2>{account.name}</h2><p className="account-help" dir="ltr">{account.email}</p>{account.minecraft&&<small dir="ltr">{account.minecraft.username}</small>}</div></div>
  <nav className="account-tabs" aria-label={t('myAccount')}>{([{id:'settings',icon:Settings},{id:'connections',icon:Link2},{id:'password',icon:KeyRound},{id:'player',icon:Gamepad2}] as const).map(({id,icon:Icon})=><button type="button" key={id} aria-current={tab===id?'page':undefined} aria-pressed={tab===id} className={tab===id?'is-active':''} data-cursor="button" onClick={()=>{setTab(id);setError('');setMessage('');window.history.replaceState(null,'','/account?tab='+id);}}><Icon size={16} className="inline-block me-2" aria-hidden="true"/>{t(id)}</button>)}</nav>
  {message&&<p className="account-notice" role="status">{message}</p>}{error&&<p className="account-error" role="alert">{error}</p>}
  {tab==='settings'&&<section className="account-card"><h2>{t('settings')}</h2><form className="hub-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);const language=String(data.get('locale'));void run('settings',{name:data.get('name'),locale:language}).then(success=>{if(!success)return;document.cookie=`${LOCALE_COOKIE}=${language}; Path=/; Max-Age=31536000; SameSite=Lax`;if(language!==locale)window.location.reload();});}}><label>{t('name')}<input key={account.name} name="name" defaultValue={account.name} required minLength={2} maxLength={64} disabled={busy}/></label><label>{t('language')}<select name="locale" defaultValue={locale} disabled={busy}>{LOCALES.map(code=><option key={code} value={code}>{LOCALE_LABELS[code].native}</option>)}</select></label><button className="hub-button hub-button-primary" disabled={busy}>{t('save')}</button></form></section>}
  {tab==='password'&&<section className="account-card"><h2>{t('password')}</h2><p className="account-help">{t('passwordHint')}</p><form className="hub-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);if(data.get('password')!==data.get('confirm')){setError(t('errors.PASSWORD_MATCH'));return;}void run('password',{password:data.get('password'),nonce:data.get('nonce')});}}><label>{t('newPassword')}<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password" disabled={busy}/></label><label>{t('confirmPassword')}<input name="confirm" type="password" required minLength={12} maxLength={128} autoComplete="new-password" disabled={busy}/></label><label>{t('verificationCode')}<input name="nonce" autoComplete="one-time-code" dir="ltr" maxLength={64} disabled={busy}/><small>{t('reauthHint')}</small></label><button className="hub-button hub-button-primary" disabled={busy}>{t('save')}</button><button type="button" className="account-text-button" disabled={busy} onClick={()=>void run('reauthenticate')}>{t('sendCode')}</button></form></section>}
  {tab==='connections'&&<section className="account-card"><h2>{t('connections')}</h2><p className="account-help">{t('connectionsHint')}</p><div className="account-connections">{ACCOUNT_PROVIDERS.map(provider=>{const identities=account.providers.filter(v=>v.provider===provider);return <div key={provider} className="account-connection"><AccountIdentityIcon provider={provider} size={24}/><span>{accountProviderName(provider)}<small>{t(identities.length?'connected':'unconnected')}</small></span>{identities.length?identities.map(identity=><button key={identity.id} type="button" className="hub-button" disabled={busy||account.providers.length<2} onClick={()=>void run('unlink',{identityId:identity.id})}>{t('unlink')}</button>):<button type="button" className="hub-button" disabled={busy||!providers.includes(provider)} onClick={()=>void run('link',{provider,next:'/account?tab=connections'})}>{t('connect')}</button>}</div>;})}</div>{renderMinecraftConnection()}</section>}
  {tab==='player'&&<section className="account-card"><h2>{t('player')}</h2>{account.minecraft?<PlayerProfile linkedUsername={account.minecraft.username}/>:<><p className="account-help">{t('linkIntro')}</p>{renderMinecraftConnection()}</>}</section>}
  <Link href="/requests" className="hub-button w-fit">{t('requests')}</Link>
 </div>;
 function renderMinecraftConnection(){return <div className="account-connection mt-5"><Gamepad2 size={26}/><span>Minecraft<small>{account?.minecraft?.username??t('unconnected')}</small></span>{account?.minecraft?<button type="button" className="hub-button" disabled={busy} onClick={async()=>{setBusy(true);try{const response=await fetch('/api/account/minecraft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unlink'})});const data=await response.json();if(!response.ok)throw Error(data.error);setCode(null);await refresh();}catch(error){fail(error);}finally{setBusy(false);}}}>{t('unlink')}</button>:<form className="hub-form w-full" onSubmit={async event=>{event.preventDefault();const name=new FormData(event.currentTarget).get('username');if(!minecraftName(name)){setError(t('errors.INVALID'));return;}setBusy(true);setError('');try{const response=await fetch('/api/account/minecraft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name})});const data=await response.json();if(!response.ok)throw Error(data.error);setCode(data);}catch(error){fail(error);}finally{setBusy(false);}}}><label>{t('minecraftName')}<input name="username" required minLength={3} maxLength={32} autoCapitalize="none" spellCheck={false} dir="ltr" disabled={busy}/></label><button className="hub-button" disabled={busy}>{t('generateCode')}</button>{code&&<div className="account-link-code"><p>{t('linkInstructions')}</p><code dir="ltr">/zo7allink {code.code}</code><small>{t('linkExpiry')}</small><button type="button" className="hub-button" onClick={async()=>{try{await navigator.clipboard.writeText('/zo7allink '+code.code);setCopied(true);}catch{fail(Error('UNAVAILABLE'));}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {t('copy')}</button></div>}</form>}</div>;}
}
