"use client";
import { useCallback,useEffect,useRef,useState } from 'react';
import { useLocale,useTranslations } from 'next-intl';
import { Archive,ArrowUpRight,Award,Check,History,ImagePlus,Layers,Pencil,Plus,RefreshCw,Send,Vote,X } from 'lucide-react';
import { COMMUNITY_KINDS,COMMUNITY_LOCALES,PROJECT_STATES,safeMediaLink,type CommunityEntry,type CommunityKind } from '@/lib/data/community';
import { PLAYER_STAT_KEYS } from '@/lib/data/player-statistics';
import { communityCopy } from '@/lib/data/community-copy';
import { useCommunity } from '@/components/community/CommunityProvider';
import ContentImage from '@/components/hub/ContentImage';
import ContentImageField from './ContentImageField';
const labels={poll:'polls',gallery:'gallery',project:'projectStatus',changelog:'updates',achievement:'achievements'} as const;
const icons={poll:Vote,gallery:ImagePlus,project:Layers,changelog:History,achievement:Award};
export default function CommunityManagement({onExpired,onlyKind,onBusyChange}:{onExpired:()=>void;onlyKind?:'poll';onBusyChange?:(busy:boolean)=>void}) {
 const locale=useLocale(),c=communityCopy(locale),hub=useTranslations('hub'),dashboard=useTranslations('dashboard'),{refresh}=useCommunity();
 const [entries,setEntries]=useState<CommunityEntry[]>([]),[kind,setKind]=useState<CommunityKind>(onlyKind??'gallery'),[editing,setEditing]=useState<CommunityEntry|null>(null),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[topic,setTopic]=useState('');
 const lock=useRef(false),mounted=useRef(false);
 const reload=useCallback(async(signal?:AbortSignal)=>{try{const response=await fetch('/api/admin/community',{cache:'no-store',signal});if(response.status===401){onExpired();return;}if(!response.ok)throw Error();const data=await response.json();if(mounted.current&&!signal?.aborted){setEntries(data.entries);setMessage('');}}catch{if(mounted.current&&!signal?.aborted)setMessage('unavailable');}finally{if(mounted.current&&!signal?.aborted)setLoading(false);}},[onExpired]);
 useEffect(()=>{mounted.current=true;const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void reload(controller.signal);});return()=>{mounted.current=false;controller.abort();};},[reload]);
 const mutate=async(action:string,value:unknown)=>{if(lock.current||uploading)return false;lock.current=true;setBusy(true);onBusyChange?.(true);setMessage('');try{const response=await fetch('/api/admin/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='save'?{action,value}:{action,id:value})}),result=await response.json();if(response.status===401){onExpired();return false;}if(!response.ok)throw Error(result.error);await reload();await refresh();return true;}catch(error){if(mounted.current)setMessage(error instanceof Error&&error.message==='POLL_LOCKED'?'pollLocked':'error');return false;}finally{lock.current=false;if(mounted.current){setBusy(false);onBusyChange?.(false);}}};
 const reset=()=>{setEditing(null);setVersion(v=>v+1);},rows=entries.filter(e=>e.kind===kind&&(!topic||e.topic===topic)&&(e.title+' '+e.projectKey+' '+e.author).toLocaleLowerCase().includes(query.toLocaleLowerCase())),locked=editing?.kind==='poll'&&!!editing.votes?.some(v=>v>0),Icon=icons[kind];
 return <section className="dash-management"><div className="dash-section-heading"><div><p className="dash-eyebrow">ZO7AL PROJECTS</p><h2>{onlyKind ? c.polls : c.community}</h2></div><div className="dash-actions"><button type="button" className="dash-icon-button" disabled={busy||uploading} aria-label={hub('refresh')} onClick={()=>void reload()}><RefreshCw size={17}/></button><button type="button" className="dash-button" disabled={busy||uploading} onClick={reset}><Plus size={16}/>{c.create}</button></div></div>{!onlyKind&&<div className="hub-actions mb-6">{COMMUNITY_KINDS.filter(value=>value!=="poll").map(value=>{const Mark=icons[value];return <button key={value} type="button" className="dash-button" aria-pressed={kind===value} disabled={busy||uploading} onClick={()=>{setKind(value);reset();setMessage('');}}><Mark size={17}/>{c[labels[value]]}{value==='gallery'&&entries.some(e=>e.kind==='gallery'&&e.moderation==='pending')&&<span className="dash-nav-count">{entries.filter(e=>e.kind==='gallery'&&e.moderation==='pending').length}</span>}</button>;})}</div>}{message&&<p className="hub-error mb-5" role="alert">{c[message as 'error'|'unavailable'|'pollLocked']}</p>}<div className="dash-editor-grid"><div className="dash-panel card-glow"><div className="dash-review-filters"><input className="dash-search" value={query} onChange={e=>setQuery(e.target.value)} aria-label={dashboard('filter')} placeholder={dashboard('filter')}/><select aria-label={c.topic} value={topic} onChange={event=>setTopic(event.target.value)}><option value="">{hub("allGames")}</option><option value="minecraft">Minecraft</option><option value="fortnite">Fortnite</option></select></div><div className="community-admin-list">{rows.map(entry=>{
  const link=safeMediaLink(entry.payload.videoUrl);
  return <article key={entry.id} className="community-admin-entry"><div><h3 dir="auto">{entry.title}</h3><div className="community-meta mt-2"><span>{entry.locale.toUpperCase()}</span>{(kind==='poll'||kind==='gallery')&&<span className="dash-tag">{entry.topic==='fortnite'?'Fortnite':'Minecraft'}</span>}<span className="dash-tag">{entry.moderation==='pending'?c.pending:entry.moderation==='rejected'?c.rejected:entry.published?c.published:c.draft}</span>{entry.projectKey&&<code dir="ltr">{entry.projectKey}</code>}</div>{entry.kind==='gallery'&&<><ContentImage image={entry.image} title={entry.title}/><p dir="auto" className="mt-2">{entry.body}</p><small>{entry.author} · {entry.contactEmail}</small>{link&&<a className="dash-text-button mt-2" href={link} target="_blank" rel="noopener noreferrer">{c.mediaLink}<ArrowUpRight size={14}/></a>}</>}<div className="dash-actions mt-4"><button type="button" className="dash-button" disabled={busy||uploading} onClick={()=>{setEditing(entry);setVersion(v=>v+1);}}><Pencil size={14}/>{c.edit}</button>{!entry.published&&<button type="button" className="dash-button" disabled={busy||uploading} onClick={()=>void mutate('save',{...entry,imageId:entry.image?.id??null,published:true})}><Check size={14}/>{c.publish}</button>}{entry.published&&<button className="dash-button" type="button" disabled={busy||uploading} onClick={()=>void mutate('archive',entry.id)}><Archive size={14}/>{c.archive}</button>}{entry.kind==='gallery'&&<><button className="dash-button dash-danger" type="button" disabled={busy||uploading||entry.moderation==='rejected'} onClick={()=>void mutate('reject',entry.id)}><X size={14}/>{c.reject}</button>{entry.contactEmail&&!entry.discordReceipt&&<button className="dash-button" type="button" disabled={busy||uploading} onClick={()=>void mutate('retry',entry.id)}><Send size={14}/>{c.retry}</button>}</>}</div></div></article>;
 })}{!rows.length&&<p className="community-empty" role="status"><Icon size={20}/>{loading?c.loading:c.empty}</p>}</div></div><form key={(editing?.id??kind)+':'+version} className="dash-panel card-glow hub-form dash-editor" onSubmit={async event=>{
  event.preventDefault();if(busy||uploading)return;const form=new FormData(event.currentTarget),ends=String(form.get('endsAt')??'');
  const payload=kind==='poll'?{options:String(form.get('options')??'').split('\n').map(v=>v.trim()).filter(Boolean),endsAt:ends?new Date(ends+':00+03:00').toISOString():null}:kind==='gallery'?{videoUrl:form.get('videoUrl')}:kind==='project'?{status:form.get('status')}:kind==='changelog'?{version:form.get('version')}:{stat:form.get('stat'),threshold:Number(form.get('threshold'))*(form.get('stat')==='playtimeSeconds'?3600:1)};
  if(await mutate('save',{id:editing?.id,kind,locale:form.get('locale'),topic:form.get('topic'),projectKey:form.get('projectKey')??'',title:form.get('title'),body:form.get('body'),author:form.get('author')??'',imageId:form.get('imageId'),published:form.get('published')==='on',payload}))reset();
 }}><div className="dash-section-heading"><h3>{editing?c.edit:c.create}</h3><Icon size={20}/></div><label>{c.language}<select name="locale" defaultValue={editing?.locale??locale}>{COMMUNITY_LOCALES.map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select></label><label>{c.topic}<select name="topic" defaultValue={editing?.topic??(topic||'minecraft')} >{kind!=='poll'&&kind!=='gallery'&&<option value="all">{c.all}</option>}<option value="minecraft">Minecraft</option><option value="fortnite">Fortnite</option></select></label><label>{c.title}<input name="title" required maxLength={160} defaultValue={editing?.title??''}/></label><label>{c.body}<textarea name="body" rows={5} maxLength={10000} defaultValue={editing?.body??''}/></label>{(kind==='project'||kind==='changelog')&&<label>{c.projectKey}<input name="projectKey" required maxLength={200} dir="ltr" defaultValue={editing?.projectKey??''}/><small className="hub-muted">{c.projectHint}</small></label>}{kind==='poll'&&<><label>{c.options}<textarea name="options" required readOnly={locked} rows={5} maxLength={1000} defaultValue={(editing?.payload.options as string[]|undefined)?.join('\n')??''}/></label>{locked&&<p className="hub-muted">{c.pollLocked}</p>}<label>{c.endsAt} · {hub('riyadhTime')}<input name="endsAt" type="datetime-local" defaultValue={typeof editing?.payload.endsAt==='string'?new Date(Date.parse(editing.payload.endsAt)+10800000).toISOString().slice(0,16):''}/></label></>}{kind==='gallery'&&<><label>{c.author}<input name="author" required maxLength={64} defaultValue={editing?.author??''}/></label><ContentImageField initial={editing?.image} disabled={busy} onBusy={setUploading}/><label>{c.mediaLink}<input name="videoUrl" type="url" maxLength={1000} dir="ltr" defaultValue={String(editing?.payload.videoUrl??'')}/></label><p className="hub-muted">{c.imageOrVideo}</p></>}{kind==='project'&&<label>{c.projectStatus}<select name="status" defaultValue={String(editing?.payload.status??'development')}>{PROJECT_STATES.map(value=><option key={value} value={value}>{c[value]}</option>)}</select></label>}{kind==='changelog'&&<label>{c.version}<input name="version" required maxLength={64} defaultValue={String(editing?.payload.version??'')}/></label>}{kind==='achievement'&&<AchievementFields entry={editing}/>}<label className="hub-consent"><input type="checkbox" name="published" defaultChecked={editing?.published??false}/>{c.published}</label><div className="dash-actions"><button type="submit" className="dash-button dash-button-primary" disabled={busy||uploading}>{busy||uploading?c.loading:c.save}</button>{editing&&<button className="dash-button" type="button" disabled={busy||uploading} onClick={reset}>{c.cancel}</button>}</div></form></div></section>;
}

function AchievementFields({entry}:{entry:CommunityEntry|null}){
 const c=communityCopy(useLocale()),hub=useTranslations('hub'),[stat,setStat]=useState(String(entry?.payload.stat??'streak'));
 const multiplier=stat==='playtimeSeconds'?3600:1;
 return <><label>{c.stat}<select name="stat" value={stat} onChange={event=>setStat(event.target.value)}>{PLAYER_STAT_KEYS.map(value=><option key={value} value={value}>{hub('stat_'+value)}</option>)}</select></label><label>{c.threshold} · {hub('stat_'+stat)}<input key={stat} name="threshold" type="number" required min={0.001} max={1000000000000/multiplier} step="any" defaultValue={Number(entry?.payload.threshold??5)/multiplier}/></label><p className="hub-muted">{c.defaultGoals}</p></>;
}
