"use client";
import { useId, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { ArrowUpRight, Users, Download, Inbox, Eye, Activity, Server, ChevronRight, Video, Headphones, CalendarDays } from "lucide-react";
import BrandIcon from "@/components/ui/BrandIcon";
import type { DashboardInsights, PlatformId } from "@/lib/data/dashboard";
import type { DashboardData, ManagementTab } from "./types";

export type DashboardView = "overview" | "connections" | "console" | PlatformId | ManagementTab;
export const platformNames: Record<PlatformId,string> = {minecraft:"Minecraft",fortnite:"Fortnite",youtube:"YouTube",modrinth:"Modrinth",curseforge:"CurseForge"};
export function PlatformMark({id,size=20}:{id:PlatformId;size?:number}) { return id==="minecraft"?<Server size={size}/>:<BrandIcon slug={id} size={size}/>; }
export default function DashboardOverview({ insights,data,onView }: { insights:DashboardInsights|null;data:DashboardData;onView:(view:DashboardView)=>void }) {
  const d=useTranslations("dashboard"),h=useTranslations("hub"),locale=useLocale();
  const number=(n:number|null|undefined) => typeof n==="number"?new Intl.NumberFormat(locale).format(n):"—";
  const minecraft=insights?.platforms.find(p=>p.id==="minecraft"),modrinth=insights?.platforms.find(p=>p.id==="modrinth"),youtube=insights?.platforms.find(p=>p.id==="youtube");
  const cards=[
    {label:d("players"),value:minecraft?.metrics.players,icon:Users,color:"green",caption:minecraft?.online===true?d("serverOnline"):minecraft?.online===false?d("serverOffline"):d("waitingData"),view:"minecraft" as const},
    {label:d("downloads"),value:modrinth?.metrics.downloads,icon:Download,color:"orange",caption:"Modrinth · "+d("allTime"),view:"modrinth" as const},
    {label:d("pending"),value:insights?.summary.pending,icon:Inbox,color:"purple",caption:d("pendingHint"),view:"application" as const},
    {label:d("views"),value:youtube?.metrics.views,icon:Eye,color:"blue",caption:youtube?.status==="connected"?"YouTube · "+d("allTime"):d("setupHint"),view:"youtube" as const},
  ];
  const summary=insights?.summary,total=summary?.requests??0;
  const categories=[{key:"applications",value:summary?.applications??0,color:"#ff8b2c",icon:Video,view:"application" as const},{key:"support",value:summary?.support??0,color:"#8b7bff",icon:Headphones,view:"support" as const},{key:"registrations",value:summary?.registrations??0,color:"#40d6ac",icon:CalendarDays,view:"registrations" as const}];
  const a=total?categories[0].value/total*100:0,b=total?a+categories[1].value/total*100:0;
  return <div className="dash-overview">
    <section className="dash-welcome"><div><p className="dash-eyebrow">ZO7AL PROJECTS</p><h1>{d("welcome")} <span>Zo7al<span className="dash-orange">.</span></span></h1><p>{d("overviewHint")}</p></div><button className="dash-button dash-button-primary" type="button" onClick={()=>onView("console")}><Activity size={17}/>{d("openConsole")}<ArrowUpRight size={16}/></button></section>
    <section className="dash-stats" aria-label={d("statistics")}>{cards.map(card=><button className={"dash-panel dash-stat dash-stat-"+card.color} type="button" key={card.label} onClick={()=>onView(card.view)}><div className="dash-stat-heading"><span>{card.label}</span><span className="dash-stat-icon"><card.icon size={20}/></span></div><strong>{number(card.value)}</strong><div className="dash-stat-caption"><span>{card.caption}</span><ArrowUpRight size={16}/></div></button>)}</section>
    <div className="dash-chart-grid"><ActivityChart insights={insights}/><section className="dash-panel dash-breakdown"><div className="dash-section-heading"><div><h2>{d("requestBreakdown")}</h2><p className="dash-help">{d("allTime")}</p></div><Inbox size={19}/></div><div className="dash-donut" role="img" aria-label={d("requestBreakdown")+": "+number(summary?.requests)} style={{background:total?`conic-gradient(#ff8b2c 0% ${a}%,#8b7bff ${a}% ${b}%,#40d6ac ${b}% 100%)`:"#242730"}}><div><strong>{number(summary?.requests)}</strong><span>{d("requests")}</span></div></div><div className="dash-breakdown-legend">{categories.map(c=><button type="button" key={c.key} onClick={()=>onView(c.view)}><span style={{background:c.color}}/><span>{h(c.key)}</span><b>{number(insights?c.value:null)}</b></button>)}</div></section></div>
    <section className="dash-panel dash-platform-strip"><div className="dash-section-heading"><div><h2>{d("platforms")}</h2><p className="dash-help">{d("platformHint")}</p></div><button className="dash-text-button" type="button" onClick={()=>onView("connections")}>{d("connections")}<ChevronRight size={15}/></button></div><div className="dash-platform-grid">{(["minecraft","fortnite","youtube","modrinth","curseforge"] as const).map(id=>{const platform=insights?.platforms.find(p=>p.id===id);return <button className="dash-platform-tile" type="button" key={id} onClick={()=>onView(id)}><span className={"dash-platform-logo dash-logo-"+id}><PlatformMark id={id} size={24}/></span><strong>{platformNames[id]}</strong><span className={"dash-connection-state "+(platform?.status==="connected"?"is-connected":"")}><i/>{platform?d("connection_"+platform.status):d("waitingData")}</span></button>;})}</div></section>
    <div className="dash-bottom-grid"><section className="dash-panel"><div className="dash-section-heading"><div><h2>{d("recentActivity")}</h2><p className="dash-help">{d("recentHint")}</p></div><span className="dash-tag">{number(summary?.requests)}</span></div>{data.requests.slice(0,5).map(row=><button className="dash-recent-row" key={row.id} type="button" onClick={()=>onView(row.kind==="event"?"registrations":row.kind)}><span className="dash-item-icon">{row.kind==="application"?<Video size={18}/>:row.kind==="event"?<CalendarDays size={18}/>:<Headphones size={18}/>}</span><span className="dash-item-copy"><strong dir="auto">{String(row.payload.minecraft??row.payload.subject??row.payload.eventTitle??h(row.kind==="application"?"applications":row.kind==="event"?"registrations":"support"))}</strong><small>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(new Date(row.createdAt))}</small></span><span className="dash-tag">{h("status_"+row.status)}</span></button>)}{!data.requests.length&&<div className="dash-empty"><Inbox size={28}/><p>{h("empty")}</p></div>}</section>
      <section className="dash-panel dash-server-card"><div className="dash-section-heading"><h2>Minecraft</h2><Server size={19}/></div><div className="dash-server-visual" aria-hidden="true"><Server size={48}/><span className={minecraft?.online?"is-connected":""}/></div><span className={"dash-connection-state "+(minecraft?.online?"is-connected":"")}><i/>{minecraft?.online===true?d("serverOnline"):minecraft?.online===false?d("serverOffline"):d("waitingData")}</span><strong dir="ltr">{minecraft?.address??"zo7al.play-mc.fun"}</strong><p className="dash-help" dir="auto">{minecraft?.version??"—"}</p><div className="dash-server-count"><Users size={16}/><b>{number(minecraft?.metrics.players)}</b><span>/ {number(minecraft?.metrics.capacity)}</span></div><button className="dash-button" type="button" onClick={()=>onView("console")}><Activity size={16}/>{d("openConsole")}<ArrowUpRight size={15}/></button></section></div>
  </div>;
}

function ActivityChart({insights}:{insights:DashboardInsights|null}) {
  const d=useTranslations("dashboard"),h=useTranslations("hub"),locale=useLocale(),id=useId().replaceAll(":","");
  const [period,setPeriod]=useState(28),[hover,setHover]=useState<number|null>(null);
  const rows=insights?.activity.slice(-period)??[];
  const max=Math.max(1,...rows.flatMap(row=>[row.requests,row.orders]));
  const x=(i:number)=>44+i*(596/Math.max(1,rows.length-1)),y=(v:number)=>172-v/max*136;
  const line=(key:"requests"|"orders")=>rows.map((row,i)=>(i?"L":"M")+x(i)+","+y(row[key])).join(" ");
  const total=rows.reduce((n,row)=>n+row.requests+row.orders,0),selected=hover===null?null:rows[hover];
  const format=(n:number)=>new Intl.NumberFormat(locale).format(n);
  return <section className="dash-panel dash-activity-chart"><div className="dash-section-heading"><div><h2>{d("activity")}</h2><p className="dash-help">{d("activityHint")}</p></div><div className="dash-period" role="group" aria-label={d("period")}>{[7,28].map(value=><button key={value} type="button" aria-pressed={period===value} onClick={()=>{setPeriod(value);setHover(null);}}>{d("days",{count:value})}</button>)}</div></div><div className="dash-chart-total"><strong>{insights?format(total):"—"}</strong><span>{d("activityTotal")}</span></div><div className="dash-chart" onMouseLeave={()=>setHover(null)}><svg viewBox="0 0 672 210" role="img" aria-label={d("activity")}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff8b2c" stopOpacity=".21"/><stop offset="100%" stopColor="#ff8b2c" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i=><g key={i}><line x1="44" x2="640" y1={36+i*34} y2={36+i*34} stroke="#272a32" strokeDasharray="3 5"/><text x="30" y={40+i*34} textAnchor="end" fill="#757d8d" fontSize="10">{format(Math.round(max*(1-i/4)))}</text></g>)}{rows.length>0&&<><path d={line("requests")+` L640,172 L44,172 Z`} fill={`url(#${id})`}/><path d={line("requests")} fill="none" stroke="#ff8b2c" strokeWidth="2.7"/><path d={line("orders")} fill="none" stroke="#8b7bff" strokeWidth="2"/>{rows.map((row,i)=><rect key={row.day} x={x(i)-10} y="24" width="20" height="153" fill="transparent" tabIndex={0} role="button" aria-label={row.day+": "+d("requests")+" "+format(row.requests)+", "+h("orders")+" "+format(row.orders)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)} onMouseEnter={()=>setHover(i)}/>)}{[0,Math.floor((rows.length-1)/2),rows.length-1].map(i=><text key={i} x={x(i)} y="201" textAnchor="middle" fill="#757d8d" fontSize="11">{new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(rows[i].day+"T12:00:00Z"))}</text>)}{hover!==null&&selected&&<><line x1={x(hover)} x2={x(hover)} y1="28" y2="172" stroke="#687083" strokeDasharray="3 3"/><circle cx={x(hover)} cy={y(selected.requests)} r="4" fill="#ff8b2c" stroke="#16191f" strokeWidth="2"/></>}</>}</svg>{selected&&<div className="dash-chart-tooltip" role="status"><b>{selected.day}</b><span>{d("requests")}: {format(selected.requests)}</span><span>{h("orders")}: {format(selected.orders)}</span></div>}</div><div className="dash-chart-legend"><span><i style={{background:"#ff8b2c"}}/>{d("requests")}</span><span><i style={{background:"#8b7bff"}}/>{d("registeredCarts")}</span><small>{d("riyadh")}</small></div></section>;
}
