"use client";
import { useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { ArrowUpRight, KeyRound, ShieldCheck, Plug, Server, AlertCircle, Terminal } from "lucide-react";
import type { DashboardConnection, PlatformData, PlatformId, ConnectionProvider, MetricKey } from "@/lib/data/dashboard";
import { connectionProviders } from "@/lib/data/dashboard";
import { PlatformMark, platformNames, type DashboardView } from "./DashboardOverview";
import MinecraftBridgeSettings from "./MinecraftBridgeSettings";

const portals:Record<PlatformId,string>={minecraft:"/minecraft",fortnite:"https://create.fortnite.com/",youtube:"https://studio.youtube.com/",modrinth:"https://modrinth.com/user/iiZo7al",curseforge:"https://www.curseforge.com/minecraft"};
const metrics:Record<PlatformId,MetricKey[]>={minecraft:["players","capacity"],fortnite:["plays","minutesPlayed","projects"],youtube:["subscribers","views","videos"],modrinth:["downloads","followers","projects"],curseforge:["downloads","projects"]};
export function DashboardPlatform({id,platform,onView}:{id:PlatformId;platform?:PlatformData;onView:(view:DashboardView)=>void}) {
  const d=useTranslations("dashboard"),locale=useLocale();
  const number=(n:number|null|undefined)=>typeof n==="number"?new Intl.NumberFormat(locale).format(n):"—";
  return <section><div className="dash-platform-heading"><span className={"dash-platform-logo dash-logo-"+id}><PlatformMark id={id} size={30}/></span><div><p className="dash-eyebrow">{d("platformAnalytics")}</p><h1>{platformNames[id]}</h1></div><a className="dash-button" href={portals[id]} target={id==="minecraft"?undefined:"_blank"} rel="noopener noreferrer">{d("openPlatform")}<ArrowUpRight size={16}/></a></div><p className="dash-help dash-platform-description">{d("description_"+id)}</p>
    <div className="dash-platform-metrics">{metrics[id].map(key=><div className="dash-panel card-glow dash-stat" key={key}><span className="dash-help">{d(key)}</span><strong>{number(platform?.metrics[key])}</strong><small>{d(id==="fortnite"?"last7Days":key==="players"||key==="capacity"?"live":"allTime")}</small></div>)}</div>
    <div className="dash-panel card-glow dash-source"><span className={"dash-connection-state "+(platform?.status==="connected"?"is-connected":"")}><i/>{platform?d("connection_"+platform.status):d("waitingData")}</span><span>{d("source")}: {id==="minecraft"?"MCStatus":id==="fortnite"?"Epic Games Data API":platformNames[id]+" API"}</span>{platform?.updatedAt&&<time dateTime={platform.updatedAt}>{new Intl.DateTimeFormat(locale,{timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(platform.updatedAt))}</time>}</div>
    {id==="fortnite"&&<p className="dash-help dash-info"><AlertCircle size={16}/>{d("coverageHint",{available:platform?.coverage?.available??0,total:platform?.coverage?.total??0})}</p>}
    {platform?.status==="setup"&&<div className="dash-panel card-glow dash-setup"><KeyRound size={32}/><h2>{d("setupTitle")}</h2><p>{d("setupHint")}</p><button className="dash-button dash-button-primary" type="button" onClick={()=>onView("connections")}><Plug size={16}/>{d("connect")}</button></div>}
    {id==="minecraft"?<div className="dash-panel card-glow dash-minecraft-detail"><Server size={42}/><div><h2 dir="ltr">{platform?.address??"zo7al.play-mc.fun"}</h2><p className="dash-help" dir="auto">{platform?.version??"—"}</p><span className="dash-tag">{platform?.online===true?d("serverOnline"):platform?.online===false?d("serverOffline"):d("waitingData")}</span></div><button className="dash-button dash-button-primary" type="button" onClick={()=>onView("console")}><Terminal size={16}/>{d("openConsole")}</button></div>:<div className="dash-projects">{platform?.items.map(item=><article className="dash-panel card-glow dash-project" key={item.id}><div className="dash-section-heading"><h2 dir="auto">{item.title}</h2><a className="dash-icon-button" href={item.url} target="_blank" rel="noopener noreferrer" aria-label={d("openPlatform")+" · "+item.title}><ArrowUpRight size={18}/></a></div>{id==="fortnite"&&<bdi className="dash-reference">{item.id}</bdi>}<dl>{Object.entries(item.metrics).map(([key,value])=><div key={key}><dt>{d(key)}</dt><dd>{number(value)}</dd></div>)}</dl>{item.updatedAt&&<p className="dash-help">{d("updated")}: {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(new Date(item.updatedAt))}</p>}</article>)}</div>}
  </section>;
}
export function DashboardConnections({connections,onSaved,onExpired}:{connections:DashboardConnection[];onSaved:(connections:DashboardConnection[])=>void;onExpired:()=>void}) {
  const d=useTranslations("dashboard");
  return <section><div className="dash-section-heading"><div><p className="dash-eyebrow">ZO7AL PROJECTS</p><h1>{d("connections")}</h1></div><ShieldCheck size={24}/></div><p className="dash-help dash-platform-description">{d("connectionHint")}</p><div className="dash-connections-grid">{connectionProviders.map(provider=><ConnectionForm key={provider} provider={provider} connection={connections.find(c=>c.provider===provider)} onSaved={onSaved} onExpired={onExpired}/>)}</div><MinecraftBridgeSettings onExpired={onExpired}/><div className="dash-panel card-glow dash-public-connections"><h2>{d("publicConnections")}</h2>{(["minecraft","fortnite","modrinth"] as const).map(id=><div key={id}><PlatformMark id={id}/><strong>{platformNames[id]}</strong><span className="dash-tag dash-tag-green">{d("publicAPI")}</span></div>)}</div></section>;
}
function ConnectionForm({provider,connection,onSaved,onExpired}:{provider:ConnectionProvider;connection?:DashboardConnection;onSaved:(connections:DashboardConnection[])=>void;onExpired:()=>void}) {
  const d=useTranslations("dashboard"),h=useTranslations("hub");
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  return <form className="dash-panel card-glow hub-form dash-connection-form" onSubmit={async e=>{
    e.preventDefault();if(busy||connection?.managedByEnvironment)return;const form=e.currentTarget,values=new FormData(form);setBusy(true);setMessage("");
    try {const response=await fetch("/api/admin/connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider,apiKey:values.get("apiKey"),account:values.get("account")??"iiZo7al",panelUrl:values.get("panelUrl")})});if(response.status===401){onExpired();return;}if(!response.ok)throw Error(response.status===429?"rateLimit":"connectionFailed");const result=await response.json();(form.elements.namedItem("apiKey") as HTMLInputElement).value="";onSaved(result.connections);setMessage("connectedSuccess");}catch(error){setMessage(error instanceof Error?error.message:"connectionFailed");}finally{setBusy(false);}
  }}><div className="dash-section-heading"><span className={"dash-platform-logo dash-logo-"+provider}>{provider==="pelican"?<Terminal size={25}/>:<PlatformMark id={provider} size={25}/>}</span><span className={"dash-tag "+(connection?.configured?"dash-tag-green":"")}>{d(connection?.configured?"connection_connected":"connection_setup")}</span></div><h2>{provider==="pelican"?"Pelican":platformNames[provider]}</h2><p className="dash-help">{d("connect_"+provider)}</p>{provider==="pelican"&&<label>{d("panelUrl")}<input name="panelUrl" type="url" required maxLength={250} placeholder="https://panel.example.com" defaultValue={connection?.panelUrl??""} disabled={connection?.managedByEnvironment} dir="ltr"/></label>}{provider!=="curseforge"&&<label>{d(provider==="pelican"?"serverId":"channelHandle")}<input name="account" required maxLength={60} placeholder={provider==="pelican"?"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx":"iiZo7al"} defaultValue={connection?.account??(provider==="pelican"?"":"iiZo7al")} disabled={connection?.managedByEnvironment} dir="ltr"/></label>}<label>{d(provider==="pelican"?"clientKey":"apiKey")}<input name="apiKey" type="password" required minLength={20} maxLength={256} autoComplete="off" placeholder={connection?.configured?"••••••••••••••••":""} disabled={connection?.managedByEnvironment} dir="ltr"/></label>{connection?.managedByEnvironment?<p className="dash-help">{d("managedEnvironment")}</p>:<button className="dash-button dash-button-primary" type="submit" disabled={busy}><Plug size={16}/>{busy?h("loading"):d(connection?.configured?"updateConnection":"connect")}</button>}{message&&<p role="status" className={message==="connectedSuccess"?"dash-success":"hub-error"}>{message==="rateLimit"?h(message):d(message)}</p>}<small className="dash-help"><ShieldCheck size={14}/>{d("encrypted")}</small></form>;
}
