"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import { AnimatePresence, motion } from "framer-motion";
import { LayoutDashboard, Newspaper, CalendarDays, Shield, Video, Headphones, ClipboardList, ShoppingBag, Plug, Terminal, Menu, X, RefreshCw, ArrowUpRight, LogOut, LockKeyhole, ShieldCheck, ChevronRight, Users } from "lucide-react";
import LanguageSwitcher from "@/components/layout/LanguageSwitcher";
import DetailsDialog from "@/components/ui/DetailsDialog";
import type { DashboardConnection, DashboardInsights } from "@/lib/data/dashboard";
import { platformIds } from "@/lib/data/dashboard";
import DashboardOverview, { PlatformMark, platformNames, type DashboardView } from "./DashboardOverview";
import DashboardManagement from "./DashboardManagement";
import CommunityManagement from "./CommunityManagement";
import { communityCopy } from "@/lib/data/community-copy";
import { DashboardConnections, DashboardPlatform } from "./DashboardPlatforms";
import dynamic from "next/dynamic";
import SearchIcon from "@/components/ui/SearchIcon";
const PelicanWorkspace=dynamic(()=>import("./PelicanWorkspace"),{loading:()=> <div className="dash-panel card-glow dash-empty" aria-busy="true"><RefreshCw size={24} className="dash-spinning"/></div>});
const YouTubeWorkspace=dynamic(()=>import("./YouTubeWorkspace"),{loading:()=> <div className="dash-panel card-glow dash-empty" aria-busy="true"><RefreshCw size={24} className="dash-spinning"/></div>});
import { emptyDashboard, type DashboardData, type ManagementTab, type Mutate } from "./types";

const management=[{id:"news",label:"news",icon:Newspaper},{id:"event",label:"events",icon:CalendarDays},{id:"rule",label:"rules",icon:Shield},{id:"application",label:"applications",icon:Video},{id:"support",label:"support",icon:Headphones},{id:"registrations",label:"registrations",icon:ClipboardList},{id:"orders",label:"orders",icon:ShoppingBag},{id:"community",label:"community",icon:Users}] as const;
const blankState={configured:false,authenticated:false,checked:false};
export default function Dashboard() {
  const d=useTranslations("dashboard"),h=useTranslations("hub"),locale=useLocale();
  const [session,setSession]=useState(blankState),[data,setData]=useState<DashboardData>(emptyDashboard),[insights,setInsights]=useState<DashboardInsights|null>(null),[connections,setConnections]=useState<DashboardConnection[]>([]),[view,setView]=useState<DashboardView>("overview"),[drawer,setDrawer]=useState(false),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState("");
  const inflight=useRef<Promise<void>|null>(null),sessionGeneration=useRef(0);
  const expire=useCallback(()=>{sessionGeneration.current++;setSession(previous=>({...previous,authenticated:false}));setData(emptyDashboard);setInsights(null);setConnections([]);setMessage("sessionExpired");},[]);
  const reload=useCallback(async(signal?:AbortSignal,force=false)=>{
    if(inflight.current){await inflight.current;if(!force)return;}
    if(signal?.aborted)return;
    setRefreshing(true);const generation=sessionGeneration.current;
    const task=(async()=>{
      const results=await Promise.allSettled(["hub","insights","connections"].map(async endpoint=>{const response=await fetch("/api/admin/"+endpoint,{cache:"no-store",signal});if(response.status===401)throw Error("sessionExpired");if(!response.ok)throw Error("unavailable");return response.json();}));
      if(signal?.aborted||generation!==sessionGeneration.current)return;
      if(results.some(result=>result.status==="rejected"&&result.reason?.message==="sessionExpired")){expire();return;}
      if(results[0].status==="fulfilled")setData(results[0].value);if(results[1].status==="fulfilled")setInsights(results[1].value);if(results[2].status==="fulfilled")setConnections(results[2].value.connections);
      if(results.some(result=>result.status==="rejected"))setMessage("unavailable");
    })();
    inflight.current=task;
    try {await task;} finally {if(inflight.current===task)inflight.current=null;if(!signal?.aborted)setRefreshing(false);}
  },[expire]);
  useEffect(()=>{const controller=new AbortController();void fetch("/api/admin/session",{signal:controller.signal,cache:"no-store"}).then(response=>{if(!response.ok)throw Error("unavailable");return response.json();}).then(result=>{if(!controller.signal.aborted)setSession({...result,checked:true});}).catch(()=>{if(!controller.signal.aborted){setSession({...blankState,checked:true});setMessage("unavailable");}});return()=>controller.abort();},[]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const requested=params.get("view");if(requested==="youtube"||requested==="modrinth"||requested==="community")queueMicrotask(()=>setView(requested));},[]);
  useEffect(()=>{if(!session.authenticated)return;const controller=new AbortController();queueMicrotask(()=>void reload(controller.signal,true));const interval=setInterval(()=>{if(document.visibilityState==="visible")void reload(controller.signal);},60000);return()=>{controller.abort();clearInterval(interval);};},[session.authenticated,reload]);
  const mutate:Mutate=async(action,value)=>{
    if(busy)return false;setBusy(true);setMessage("");
    try {const response=await fetch("/api/admin/hub",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="delete"||action==="retryDiscord"||action==="retryApplication"?{action,id:value}:{action,value})});if(response.status===401){expire();return false;}if(!response.ok)throw Error(response.status===429?"rateLimit":"unavailable");await reload(undefined,true);setMessage("saved");return true;}catch(error){setMessage(error instanceof Error?error.message:"unavailable");return false;}finally{setBusy(false);}
  };
  const onView=(next:DashboardView)=>{setView(next);setDrawer(false);setMessage("");window.scrollTo({top:0,behavior:"instant"});};
  const brand=<><span className="dash-brand-dot" aria-hidden="true"/><span>Zo7al<br/>Projects</span></>;
  const title=view==="community"?communityCopy(locale).community:view==="overview"?d("overview"):view==="connections"?d("connections"):view==="console"?d("pelicanTitle"):platformIds.includes(view as typeof platformIds[number])?platformNames[view as typeof platformIds[number]]:h(management.find(item=>item.id===view)?.label??"news");
  const navigation=<><div className="dash-brand">{brand}<span className="dash-tag">{d("dashboard")}</span></div><nav className="dash-navigation" aria-label={d("dashboard")}><p>{d("workspace")}</p><button type="button" aria-current={view==="overview"?"page":undefined} onClick={()=>onView("overview")}><LayoutDashboard size={18}/><span>{d("overview")}</span></button><button type="button" aria-current={view==="console"?"page":undefined} onClick={()=>onView("console")}><Terminal size={18}/><span>Pelican</span></button><p>{d("platforms")}</p>{platformIds.map(id=><button key={id} type="button" aria-current={view===id?"page":undefined} onClick={()=>onView(id)}><PlatformMark id={id} size={18}/><span>{platformNames[id]}</span><i className={"dash-nav-dot "+(insights?.platforms.find(p=>p.id===id)?.status==="connected"?"is-connected":"")}/></button>)}<p>{d("manage")}</p>{management.map(item=><button key={item.id} type="button" aria-current={view===item.id?"page":undefined} onClick={()=>onView(item.id)}><item.icon size={18}/><span>{item.id==="community"?communityCopy(locale).community:h(item.label)}</span>{item.id==="application"&&!!insights?.summary.pending&&<span className="dash-nav-count">{insights.summary.pending}</span>}</button>)}<p>{d("settings")}</p><button type="button" aria-current={view==="connections"?"page":undefined} onClick={()=>onView("connections")}><Plug size={18}/><span>{d("connections")}</span></button></nav><div className="dash-sidebar-footer"><span className="dash-owner-avatar">Z</span><div><strong>Zo7al</strong><small>{d("owner")}</small></div><ShieldCheck size={17}/></div></>;
  if(!session.authenticated)return <div className="dash-login-layout"><header><Link href="/" className="dash-brand">{brand}</Link><LanguageSwitcher/></header><div className="dash-login-container"><section className="dash-login-intro"><p className="dash-eyebrow">ZO7AL PROJECTS · DASHBOARD</p><h1>{d("loginTitle")}<span>.</span></h1><p>{d("loginHint")}</p><div className="dash-login-platforms">{platformIds.map(id=><span key={id} title={platformNames[id]} className={"dash-platform-logo dash-logo-"+id}><PlatformMark id={id} size={24}/></span>)}</div><div className="dash-login-orbit" aria-hidden="true"><div/><div/><div/><Image src="/icon.svg" width={96} height={96} alt=""/></div></section><section className="dash-panel card-glow dash-login-card"><span className="dash-login-lock"><LockKeyhole size={28}/></span><p className="dash-eyebrow">{d("privateWorkspace")}</p><h2>{d("dashboard")}</h2><p className="dash-help">{d("signInHint")}</p><form className="hub-form" onSubmit={async event=>{
    event.preventDefault();if(busy||!session.configured)return;const form=event.currentTarget,password=new FormData(form).get("password");setBusy(true);setMessage("");try{const response=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(!response.ok)throw Error(response.status===429?"rateLimit":response.status===401?"invalidPassword":"unavailable");form.reset();sessionGeneration.current++;setSession(previous=>({...previous,authenticated:true}));}catch(error){setMessage(error instanceof Error?error.message:"unavailable");}finally{setBusy(false);}
  }}><label>{h("password")}<input type="password" name="password" minLength={16} maxLength={128} required autoComplete="current-password" disabled={!session.checked||busy} dir="ltr"/></label><button type="submit" className="dash-button dash-button-primary" disabled={!session.checked||!session.configured||busy}>{h(!session.checked||busy?"loading":"login")}<ChevronRight size={17}/></button>{session.checked&&!session.configured&&<p className="hub-error">{h("adminUnavailable")}</p>}{message&&<p role="alert" className="hub-error">{h.has(message)?h(message):h("unavailable")}</p>}</form><small className="dash-help"><ShieldCheck size={14}/>{d("sessionProtected")}</small></section></div><footer><Link href="/" className="dash-text-button">{d("returnSite")}<ArrowUpRight size={15}/></Link><span>© {new Date().getFullYear()} Zo7al Projects</span></footer></div>;
  return <div className="dash-shell"><aside className="dash-sidebar">{navigation}</aside><div className="dash-main"><header className="dash-topbar"><div className="dash-breadcrumb"><button className="dash-icon-button dash-mobile-menu" type="button" aria-label={d("menu")} onClick={()=>setDrawer(true)}><Menu size={20}/></button><span>{d("dashboard")}</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="dash-topbar-actions"><button className="dash-icon-button" type="button" aria-label={h("search")} onClick={()=>window.dispatchEvent(new CustomEvent("zo7al-search"))}><SearchIcon size={18}/></button><button className="dash-icon-button" type="button" aria-label={h("refresh")} disabled={refreshing} onClick={()=>void reload()}><RefreshCw size={17} className={refreshing?"dash-spinning":""}/></button><LanguageSwitcher/><Link href="/" className="dash-button dash-return">{d("returnSite")}<ArrowUpRight size={15}/></Link><button className="dash-icon-button" type="button" aria-label={h("logout")} disabled={busy} onClick={async()=>{setBusy(true);try{const response=await fetch("/api/admin/logout",{method:"POST"});if(!response.ok)throw Error("unavailable");sessionGeneration.current++;setSession(previous=>({...previous,authenticated:false}));setData(emptyDashboard);setInsights(null);setConnections([]);setMessage("");}catch{setMessage("unavailable");}finally{setBusy(false);}}}><LogOut size={17}/></button></div></header><div className="dash-content">{message&&<div className={"dash-notice "+(message==="saved"?"dash-success":"hub-error")} role="status"><span>{h.has(message)?h(message):h("unavailable")}</span><button type="button" className="dash-icon-button" aria-label={d("close")} onClick={()=>setMessage("")}><X size={15}/></button></div>}
      <AnimatePresence mode="wait" initial={false}><motion.div key={view} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-4}} transition={{duration:.17}}>{view==="overview"?<DashboardOverview insights={insights} data={data} onView={onView}/>:view==="connections"?<DashboardConnections connections={connections} onSaved={value=>{setConnections(value);void reload(undefined,true);}} onExpired={expire}/>:view==="console"?<PelicanWorkspace account={connections.find(value=>value.provider==="pelican")?.account} panelUrl={connections.find(value=>value.provider==="pelican")?.panelUrl} onConnections={()=>onView("connections")} onExpired={expire}/>:view==="youtube"?<YouTubeWorkspace onExpired={expire}/>:platformIds.includes(view as typeof platformIds[number])?<DashboardPlatform onExpired={expire} connections={connections} onSaved={value=>{setConnections(value);void reload(undefined,true);}} id={view as typeof platformIds[number]} platform={insights?.platforms.find(p=>p.id===view)} onView={onView}/>:view==="community"?<CommunityManagement onExpired={expire}/>:<DashboardManagement key={view} tab={view as ManagementTab} data={data} busy={busy} mutate={mutate}/>}</motion.div></AnimatePresence><footer className="dash-page-footer"><span>Zo7al Projects · {d("dashboard")}</span><span>{insights?d("updated")+" "+new Intl.DateTimeFormat(locale,{timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(insights.generatedAt))+" · "+d("riyadh"):d("waitingData")}</span></footer></div></div>{drawer&&<DetailsDialog title={d("menu")} onClose={()=>setDrawer(false)} style={{width:"min(360px,calc(100vw - 24px))",maxHeight:"90dvh"}}><div className="dash-drawer">{navigation}</div></DetailsDialog>}</div>;
}
