"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { CalendarClock, Plus, Pencil, Trash2, Play, Clock, Terminal } from "lucide-react";
import { collection, object, string } from "@/lib/data/pelican-management";
import { PelicanContent, PelicanEmpty, PelicanFeedback, PelicanForm, usePelicanActions, usePelicanFormat, usePelicanResource, type Field, type OperationForm, type PelicanContext } from "./pelican-ui";
const scheduleFields:Field[]=[{name:"name",required:true},{name:"minute",required:true,dir:"ltr"},{name:"hour",required:true,dir:"ltr"},{name:"day_of_month",label:"dayMonth",required:true,dir:"ltr"},{name:"month",required:true,dir:"ltr"},{name:"day_of_week",label:"dayWeek",required:true,dir:"ltr"},{name:"is_active",label:"active",type:"checkbox"},{name:"only_when_online",label:"onlyOnline",type:"checkbox"}];
const taskFields:Field[]=[{name:"taskAction",type:"select",options:[{value:"command",label:"command"},{value:"power",label:"power"},{value:"backup",label:"backup"},{value:"delete_files",label:"deleteFiles"}]},{name:"payload",type:"textarea",max:16000,dir:"ltr"},{name:"time_offset",label:"offset",type:"number",min:0,max:900,required:true},{name:"sequence_id",label:"sequence",type:"number",min:1,required:true},{name:"continue_on_failure",label:"continueFailure",type:"checkbox"}];
export default function PelicanSchedules({context}:{context:PelicanContext}) {
  const p=useTranslations("pelican"),format=usePelicanFormat(),state=usePelicanResource("schedules",context),actions=usePelicanActions(context,state.reload);
  const [form,setForm]=useState<OperationForm|null>(null),rows=collection(state.data);
  return <PelicanContent resource="schedules" context={context} state={state} actions={<button className="dash-button dash-button-primary" type="button" disabled={actions.busy||state.loading} onClick={()=>setForm({title:"createSchedule",action:"scheduleCreate",fields:scheduleFields,initial:{minute:"0",hour:"*",day_of_month:"*",month:"*",day_of_week:"*",is_active:true,only_when_online:false},detail:p("cronHint")})}><Plus size={17}/>{p("createSchedule")}</button>}>
    <PelicanFeedback message={actions.message}/><div className="pelican-schedule-list">{rows.map(row=>{
      const cron=object(row.cron),tasks=collection(object(row.relationships).tasks).sort((a,b)=>Number(a.sequence_id)-Number(b.sequence_id));
      const initial={id:row.id,name:row.name,...cron,is_active:row.is_active,only_when_online:row.only_when_online};
      return <article className="dash-panel card-glow pelican-schedule" key={String(row.id)}><div className="dash-section-heading"><span className="dash-item-icon"><CalendarClock size={22}/></span><div className="dash-item-copy"><h2>{string(row.name)}</h2><p><bdi className="pelican-code">{[cron.minute,cron.hour,cron.day_of_month,cron.month,cron.day_of_week].map(String).join(" ")}</bdi><span className="dash-tag">{p(row.is_processing?"processing":row.is_active?"active":"inactive")}</span></p></div><div className="dash-icon-actions"><button className="dash-icon-button" type="button" disabled={actions.busy||row.is_processing===true} title={p("runNow")} aria-label={p("runNow")} onClick={()=>setForm({title:"runNow",action:"scheduleExecute",initial:{id:row.id},fields:[],danger:"executeWarning",detail:string(row.name)})}><Play size={17}/></button><button className="dash-icon-button" type="button" disabled={actions.busy} title={p("edit")} aria-label={p("edit")} onClick={()=>setForm({title:"editSchedule",action:"scheduleUpdate",initial,fields:scheduleFields,detail:p("cronHint")})}><Pencil size={17}/></button><button className="dash-icon-button dash-danger" type="button" disabled={actions.busy} title={p("delete")} aria-label={p("delete")} onClick={()=>setForm({title:"delete",action:"scheduleDelete",initial:{id:row.id},fields:[],danger:"deleteWarning",detail:string(row.name)})}><Trash2 size={17}/></button></div></div><dl className="pelican-info-list pelican-schedule-times"><div><dt>{p("lastRun")}</dt><dd>{format.date(row.last_run_at)}</dd></div><div><dt>{p("nextRun")}</dt><dd>{format.date(row.next_run_at)}</dd></div><div><dt>{p("onlyOnline")}</dt><dd>{p(row.only_when_online?"yes":"no")}</dd></div></dl>
        <div className="pelican-tasks">{tasks.map(task=><div className="pelican-task" key={String(task.id)}><span className="dash-item-icon"><Terminal size={17}/></span><div className="dash-item-copy"><strong>{String(task.sequence_id)}. {p(task.action==="delete_files"?"deleteFiles":p.has(string(task.action))?string(task.action):"command")}</strong><pre>{string(task.payload)||"—"}</pre><small><Clock size={12}/>{p("offset")}: {String(task.time_offset)}s · {p("continueFailure")}: {p(task.continue_on_failure?"yes":"no")}</small></div><div className="dash-icon-actions"><button className="dash-icon-button" type="button" disabled={actions.busy} aria-label={p("editTask")} title={p("editTask")} onClick={()=>setForm({title:"editTask",action:"taskUpdate",initial:{scheduleId:row.id,id:task.id,taskAction:task.action,payload:task.payload,time_offset:task.time_offset,sequence_id:task.sequence_id,continue_on_failure:task.continue_on_failure},fields:taskFields,detail:p("taskHint")})}><Pencil size={15}/></button><button className="dash-icon-button dash-danger" type="button" disabled={actions.busy} aria-label={p("deleteTask")} title={p("deleteTask")} onClick={()=>setForm({title:"deleteTask",action:"taskDelete",initial:{scheduleId:row.id,id:task.id},fields:[],danger:"deleteWarning"})}><Trash2 size={15}/></button></div></div>)}</div><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"createTask",action:"taskCreate",initial:{scheduleId:row.id,taskAction:"command",time_offset:0,sequence_id:tasks.length+1,continue_on_failure:false},fields:taskFields,detail:p("taskHint")})}><Plus size={16}/>{p("createTask")}</button>
      </article>;
    })}</div>{!rows.length&&<PelicanEmpty/>}{form&&<PelicanForm form={form} busy={actions.busy} run={actions.run} onClose={()=>setForm(null)}/>}
  </PelicanContent>;
}
