"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { UserPlus, UserRound, Pencil, Trash2, ShieldCheck } from "lucide-react";
import DetailsDialog from "@/components/ui/DetailsDialog";
import { collection, pelicanPermissions, string } from "@/lib/data/pelican-management";
import { PelicanContent, PelicanEmpty, PelicanFeedback, PelicanForm, usePelicanActions, usePelicanResource, type OperationForm, type PelicanContext } from "./pelican-ui";
type UserEditor={id?:string;email:string;permissions:string[]};
const groups=Array.from(new Set(pelicanPermissions.map(permission=>permission.split(".")[0]))).filter(group=>group!=="websocket");
export default function PelicanUsers({context}:{context:PelicanContext}) {
  const p=useTranslations("pelican"),state=usePelicanResource("users",context),actions=usePelicanActions(context,state.reload);
  const [editor,setEditor]=useState<UserEditor|null>(null),[form,setForm]=useState<OperationForm|null>(null);
  const rows=collection(state.data);
  return <PelicanContent resource="users" context={context} state={state} actions={<button className="dash-button dash-button-primary" type="button" disabled={actions.busy||state.loading} onClick={()=>setEditor({email:"",permissions:["websocket.connect"]})}><UserPlus size={17}/>{p("inviteUser")}</button>}>
    <PelicanFeedback message={actions.message}/><div className="pelican-resource-grid">{rows.map(row=><article className="dash-panel card-glow pelican-resource-card" key={String(row.uuid)}><div className="dash-section-heading"><span className="dash-item-icon"><UserRound size={23}/></span>{row["2fa_enabled"]===true&&<span className="dash-tag dash-tag-green"><ShieldCheck size={13}/> 2FA</span>}</div><h2 dir="auto">{string(row.username)}</h2><p className="dash-help" dir="ltr">{string(row.email)}</p><p className="dash-help">{p("permissionCount",{count:Array.isArray(row.permissions)?row.permissions.length:0})}</p><div className="dash-actions pelican-card-actions"><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setEditor({id:string(row.uuid),email:string(row.email),permissions:Array.isArray(row.permissions)?row.permissions.filter((value):value is string=>typeof value==="string"):[]})}><Pencil size={16}/>{p("editPermissions")}</button><button className="dash-icon-button dash-danger" type="button" disabled={actions.busy} aria-label={p("removeUser")} title={p("removeUser")} onClick={()=>setForm({title:"removeUser",action:"userDelete",initial:{id:row.uuid},fields:[],danger:"removeUserWarning",detail:string(row.email)})}><Trash2 size={17}/></button></div></article>)}</div>{!rows.length&&<PelicanEmpty/>}
    {editor&&<DetailsDialog title={p(editor.id?"editPermissions":"inviteUser")} onClose={()=>{if(!actions.busy)setEditor(null);}}><form className="hub-form pelican-dialog-form" onSubmit={async event=>{event.preventDefault();const result=await actions.run(editor.id?"userUpdate":"userCreate",{id:editor.id,email:editor.email,permissions:editor.permissions,confirm:true});if(result)setEditor(null);}}><label>{p("email")}<input type="email" value={editor.email} disabled={!!editor.id} required maxLength={255} dir="ltr" autoComplete="off" onChange={event=>setEditor({...editor,email:event.target.value})}/></label><p className="dash-help">{p("permissionsHint")}</p><div className="pelican-permissions">{groups.map(group=>{
      const permissions=pelicanPermissions.filter(permission=>permission.startsWith(group+"."));
      return <fieldset key={group}><legend>{p.has("group_"+group)?p("group_"+group):group}</legend><label className="hub-consent"><input type="checkbox" checked={permissions.every(permission=>editor.permissions.includes(permission))} onChange={event=>setEditor({...editor,permissions:event.target.checked?Array.from(new Set([...editor.permissions,...permissions])):editor.permissions.filter(permission=>!permissions.includes(permission as typeof pelicanPermissions[number]))})}/>{p("selectAll")}</label>{permissions.map(permission=><label className="hub-consent" key={permission}><input type="checkbox" checked={editor.permissions.includes(permission)} onChange={event=>setEditor({...editor,permissions:event.target.checked?[...editor.permissions,permission]:editor.permissions.filter(item=>item!==permission)})}/><bdi>{permission}</bdi></label>)}</fieldset>;
    })}</div><label className="hub-consent pelican-confirm"><input type="checkbox" required/>{p("permissionsWarning")}</label><PelicanFeedback message={actions.message}/><div className="dash-actions"><button className="dash-button dash-button-primary" type="submit" disabled={actions.busy}>{p(actions.busy?"loading":"save")}</button><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setEditor(null)}>{p("cancel")}</button></div></form></DetailsDialog>}
    {form&&<PelicanForm form={form} busy={actions.busy} run={actions.run} onClose={()=>setForm(null)}/>}
  </PelicanContent>;
}
