"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { KeyRound, UserRound, Plus, Pencil, Trash2, ShieldCheck, Eye, EyeOff } from "lucide-react";
import DetailsDialog from "@/components/ui/DetailsDialog";
import { attributes, collection, object, string } from "@/lib/data/pelican-management";
import { PelicanContent, PelicanFeedback, PelicanForm, usePelicanActions, usePelicanFormat, usePelicanResource, type OperationForm, type PelicanContext } from "./pelican-ui";
import PelicanActivity from "./PelicanActivity";
export default function PelicanAccount({context}:{context:PelicanContext}) {
  const p=useTranslations("pelican"),format=usePelicanFormat(),state=usePelicanResource("account",context),keys=usePelicanResource("apiKeys",context),ssh=usePelicanResource("sshKeys",context);
  const actions=usePelicanActions(context,async()=>{await Promise.all([state.reload(),keys.reload(),ssh.reload()]);});
  const [form,setForm]=useState<OperationForm|null>(null),[secret,setSecret]=useState(""),[reveal,setReveal]=useState(false),[activity,setActivity]=useState(false);
  const account=attributes(state.data);
  return <PelicanContent resource="account" context={context} state={state}>
    <PelicanFeedback message={actions.message}/><div className="dash-panel card-glow pelican-account"><span className="dash-item-icon"><UserRound size={24}/></span><div><h2>{string(account.username)}</h2><p className="dash-help" dir="ltr">{string(account.email)}</p>{account["2fa_enabled"]===true&&<span className="dash-tag dash-tag-green"><ShieldCheck size={14}/>{p("twoFactor")}</span>}</div><div className="dash-actions"><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"username",action:"accountUsername",fields:[{name:"username",required:true,max:64,dir:"ltr"}],initial:{username:account.username},danger:"accountWarning"})}><Pencil size={15}/>{p("username")}</button><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"email",action:"accountEmail",fields:[{name:"email",type:"email",required:true,dir:"ltr"}],initial:{email:account.email},danger:"accountWarning"})}>{p("email")}</button><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"changePassword",action:"accountPassword",fields:[{name:"password",type:"password",required:true,min:16,max:128,dir:"ltr"},{name:"password_confirmation",label:"confirmPassword",type:"password",required:true,min:16,max:128,dir:"ltr"}],danger:"passwordWarning",detail:p("passwordHint")})}><KeyRound size={15}/>{p("changePassword")}</button></div></div>
    <div className="pelican-account-grid"><section className="dash-panel card-glow"><div className="dash-section-heading"><h2>{p("apiKeys")}</h2><button className="dash-icon-button" type="button" disabled={actions.busy||keys.loading} aria-label={p("createApiKey")} title={p("createApiKey")} onClick={()=>setForm({title:"createApiKey",action:"apiKeyCreate",fields:[{name:"description",required:true},{name:"allowed_ips",label:"allowedIps",type:"textarea",max:6400,dir:"ltr"}],danger:"apiKeyWarning",detail:p("allowedIpsHint")})}><Plus size={19}/></button></div><PelicanFeedback message={keys.error}/>{collection(keys.data).map(row=><article className="pelican-account-key" key={string(row.identifier)}><KeyRound size={18}/><div className="dash-item-copy"><strong>{string(row.description)||string(row.identifier)}</strong><small dir="ltr">{string(row.identifier)}</small><small>{p("lastUsed")}: {format.date(row.last_used_at)}</small><small dir="ltr">{Array.isArray(row.allowed_ips)&&row.allowed_ips.length?row.allowed_ips.map(String).join(", "):p("allIps")}</small></div><button className="dash-icon-button dash-danger" type="button" disabled={actions.busy} aria-label={p("revokeKey")} title={p("revokeKey")} onClick={()=>setForm({title:"revokeKey",action:"apiKeyDelete",fields:[],initial:{identifier:row.identifier},danger:"revokeKeyWarning",detail:string(row.description)})}><Trash2 size={17}/></button></article>)}{!keys.loading&&!collection(keys.data).length&&<p className="dash-help">{p("empty")}</p>}</section>
    <section className="dash-panel card-glow"><div className="dash-section-heading"><h2>{p("sshKeys")}</h2><button className="dash-icon-button" type="button" disabled={actions.busy||ssh.loading} aria-label={p("createSshKey")} title={p("createSshKey")} onClick={()=>setForm({title:"createSshKey",action:"sshKeyCreate",fields:[{name:"name",required:true},{name:"public_key",label:"publicKey",type:"textarea",max:16000,required:true,dir:"ltr"}],danger:"sshKeyWarning",detail:p("publicKeyHint")})}><Plus size={19}/></button></div><PelicanFeedback message={ssh.error}/>{collection(ssh.data).map(row=><article className="pelican-account-key" key={string(row.fingerprint)}><KeyRound size={18}/><div className="dash-item-copy"><strong>{string(row.name)}</strong><small className="pelican-fingerprint" dir="ltr">{string(row.fingerprint)}</small><small>{format.date(row.created_at)}</small></div><button className="dash-icon-button dash-danger" type="button" disabled={actions.busy} aria-label={p("revokeKey")} title={p("revokeKey")} onClick={()=>setForm({title:"revokeKey",action:"sshKeyDelete",fields:[],initial:{fingerprint:row.fingerprint},danger:"sshRevokeWarning",detail:string(row.name)})}><Trash2 size={17}/></button></article>)}{!ssh.loading&&!collection(ssh.data).length&&<p className="dash-help">{p("empty")}</p>}</section></div>
    <button className="dash-button" type="button" aria-expanded={activity} onClick={()=>setActivity(current=>!current)}>{p("accountActivity")}</button>{activity&&<PelicanActivity context={context} account/>}
    {form&&<PelicanForm form={form} busy={actions.busy} run={async(action,input)=>{const result=await actions.run(action,input);const token=string(object(object(result?.data).meta).secret_token);if(token){setSecret(token);setReveal(false);}return result;}} onClose={()=>setForm(null)}/>}
    {secret&&<DetailsDialog title={p("newApiKey")} onClose={()=>setSecret("")}><div className="pelican-dialog-form"><p className="dash-help">{p("oneTimeKey")}</p><div className="pelican-password"><input className="pelican-value" value={secret} type={reveal?"text":"password"} readOnly aria-label={p("newApiKey")} dir="ltr" autoComplete="off"/><button className="dash-icon-button" type="button" aria-label={p(reveal?"hide":"reveal")} onClick={()=>setReveal(current=>!current)}>{reveal?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><button className="dash-button dash-button-primary" type="button" onClick={()=>setSecret("")}>{p("close")}</button></div></DetailsDialog>}
  </PelicanContent>;
}
