"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { Pencil, Settings, Terminal, RotateCcw, KeyRound, Copy, Check } from "lucide-react";
import { attributes, collection, object, string } from "@/lib/data/pelican-management";
import { PelicanContent, PelicanEmpty, PelicanFeedback, PelicanForm, usePelicanActions, usePelicanResource, type OperationForm, type PelicanContext } from "./pelican-ui";
export default function PelicanSettings({resource,context}:{resource:"startup"|"settings";context:PelicanContext}) {
  const p=useTranslations("pelican"),state=usePelicanResource(resource,context),details=usePelicanResource(resource==="startup"?"settings":"account",context);
  const actions=usePelicanActions(context,async()=>{await Promise.all([state.reload(),details.reload()]);});
  const [form,setForm]=useState<OperationForm|null>(null),[copied,setCopied]=useState("");
  const metadata=object(object(state.data).meta),server=attributes(resource==="startup"?details.data:state.data),account=attributes(details.data),variables=collection(state.data),sftp=object(server.sftp_details),limits=object(server.limits),images=object(metadata.docker_images);
  let command=string(metadata.startup_command);
  for(const variable of variables){if(/PASSWORD|TOKEN|SECRET|KEY/i.test(string(variable.env_variable))&&string(variable.server_value))command=command.replaceAll(string(variable.server_value),"••••••••");}
  const sftpHost=string(sftp.alias)||string(sftp.ip),sftpUser=string(account.username)&&string(server.identifier)?string(account.username)+"."+string(server.identifier):"";
  const sftpURL=sftpHost&&sftpUser&&typeof sftp.port==="number"&&/^[A-Za-z0-9.-]+$/.test(sftpHost)?"sftp://"+encodeURIComponent(sftpUser)+"@"+sftpHost+":"+sftp.port:undefined;
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(value);}catch{actions.setMessage("copyFailed");}};
  return <PelicanContent resource={resource} context={context} state={state}>
    <PelicanFeedback message={actions.message}/>
    {resource==="startup"?<><article className="dash-panel card-glow pelican-startup-command"><div className="dash-section-heading"><h2>{p("startupCommand")}</h2><Terminal size={22}/></div><pre className="pelican-code">{command||"—"}</pre>{Object.keys(images).length>0&&<form className="hub-form pelican-image-form" onSubmit={async event=>{event.preventDefault();const docker_image=new FormData(event.currentTarget).get("docker_image");await actions.run("dockerImage",{docker_image});}}><label>{p("dockerImage")}<select name="docker_image" key={string(server.docker_image)} defaultValue={string(server.docker_image)}>{Object.entries(images).map(([name,image])=><option key={String(image)} value={String(image)}>{name} · {String(image)}</option>)}</select></label><button className="dash-button" type="submit" disabled={actions.busy||details.loading}>{p("save")}</button></form>}</article><div className="pelican-resource-grid">{variables.map(variable=>{
      const secret=/PASSWORD|TOKEN|SECRET|KEY/i.test(string(variable.env_variable));
      return <article className="dash-panel card-glow pelican-resource-card" key={string(variable.env_variable)}><div className="dash-section-heading"><h2>{string(variable.name)}</h2><span className="dash-tag">{p(variable.is_editable?"editable":"readOnly")}</span></div><p className="dash-help">{string(variable.description)}</p><bdi className="pelican-variable-name">{string(variable.env_variable)}</bdi><input className="pelican-value" type={secret?"password":"text"} value={string(variable.server_value)} readOnly dir="ltr" aria-label={string(variable.name)} autoComplete="off"/><p className="dash-help">{p("rules")}: {string(variable.rules)}</p><button className="dash-button" type="button" disabled={actions.busy||variable.is_editable!==true} onClick={()=>setForm({title:"editVariable",action:"startupUpdate",initial:{key:variable.env_variable,value:variable.server_value},fields:[{name:"value",type:secret?"password":"text",max:16000,dir:"ltr"}],detail:string(variable.description)+" · "+string(variable.rules)})}><Pencil size={16}/>{p("edit")}</button></article>;
    })}</div>{!variables.length&&<PelicanEmpty/>}</>:<div className="pelican-resource-grid">
      <article className="dash-panel card-glow pelican-resource-card"><div className="dash-section-heading"><h2>{p("serverInfo")}</h2><Settings size={22}/></div><dl className="pelican-info-list"><div><dt>{p("name")}</dt><dd>{string(server.name)}</dd></div><div><dt>{p("description")}</dt><dd>{string(server.description)||"—"}</dd></div><div><dt>{p("uuid")}</dt><dd dir="ltr">{string(server.uuid)}</dd></div><div><dt>{p("node")}</dt><dd>{string(server.node)||"—"}</dd></div></dl><div className="dash-actions pelican-card-actions"><button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"rename",action:"serverRename",initial:{name:server.name},fields:[{name:"name",required:true}]})}><Pencil size={16}/>{p("rename")}</button>{"description" in server&&<button className="dash-button" type="button" disabled={actions.busy} onClick={()=>setForm({title:"description",action:"serverDescription",initial:{description:server.description},fields:[{name:"description",type:"textarea",max:4000}]})}>{p("description")}</button>}</div></article>
      <article className="dash-panel card-glow pelican-resource-card"><div className="dash-section-heading"><h2>SFTP</h2><KeyRound size={22}/></div><p className="dash-help">{p("sftpHint")}</p><dl className="pelican-info-list"><div><dt>{p("host")}</dt><dd dir="ltr">{sftpHost||"—"}</dd></div><div><dt>{p("port")}</dt><dd>{String(sftp.port??"—")}</dd></div><div><dt>{p("username")}</dt><dd dir="ltr">{sftpUser||"—"}</dd></div></dl><div className="dash-actions pelican-card-actions">{sftpURL&&<a className="dash-button" href={sftpURL}>{p("openSftp")}</a>}<button className="dash-icon-button" type="button" disabled={!sftpUser} aria-label={p("copy")} title={p("copy")} onClick={()=>void copy(sftpUser)}>{copied===sftpUser?<Check size={17}/>:<Copy size={17}/>}</button></div></article>
      <article className="dash-panel card-glow pelican-resource-card"><h2>{p("limits")}</h2><dl className="pelican-info-list">{["memory","disk","cpu","swap","io"].map(key=><div key={key}><dt>{p(key)}</dt><dd>{limits[key]===0&&["memory","disk","cpu"].includes(key)?p("unlimited"):typeof limits[key]==="number"?String(limits[key])+(key==="cpu"?"%":key==="io"?"":" MiB"):"—"}</dd></div>)}</dl><p className="dash-help">{p("limitsHint")}</p></article>
      <article className="dash-panel card-glow pelican-resource-card pelican-danger-card"><h2>{p("reinstall")}</h2><p className="dash-help">{p("reinstallHint")}</p><button className="dash-button dash-danger" type="button" disabled={actions.busy} onClick={()=>setForm({title:"reinstall",action:"serverReinstall",fields:[],initial:{},danger:"reinstallWarning",detail:string(server.name)})}><RotateCcw size={16}/>{p("reinstall")}</button></article>
    </div>}
    {form&&<PelicanForm form={form} busy={actions.busy} run={actions.run} onClose={()=>setForm(null)}/>}
  </PelicanContent>;
}
