"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { Plus, Radio, Trash2, Link2 } from "lucide-react";
import { youtubeObject as object, youtubeItems as items, youtubeString as string } from "@/lib/data/youtube-studio";
import { useYoutubeResource, useYoutubeActions, useYoutubePages, useYoutubeFormat, YoutubeSection, YoutubeFeedback, YoutubeForm, YoutubePages, privacyField, type StudioContext, type StudioForm } from "./youtube-ui";
export default function YouTubeLive({ onExpired }: StudioContext) {
  const y = useTranslations("youtubeStudio"), pages = useYoutubePages(), state = useYoutubeResource("live", { onExpired }, { pageToken: pages.token }), actions = useYoutubeActions({ onExpired }, state.reload), [form, setForm] = useState<StudioForm | null>(null), format = useYoutubeFormat();
  const streams = items({ items: state.data?.streams }).map(value => ({ value: string(value.id), label: string(object(value.snippet).title) }));
  return <YoutubeSection title="live" state={state} actions={<button className="dash-button dash-button-primary" type="button" disabled={actions.busy} onClick={() => setForm({ title: "createLive", action: "liveCreate", fields: [{ name: "title", required: true, max: 100 }, { name: "description", type: "textarea", max: 5000 }, { name: "scheduledStartTime", type: "datetime-local", required: true }, privacyField, { name: "selfDeclaredMadeForKids", type: "checkbox" }], initial: { privacyStatus: "private" } })}><Plus size={16} />{y("createLive")}</button>}><p className="dash-help">{y("liveHint")}</p><YoutubeFeedback message={actions.message} />{!items(state.data).length && <div className="dash-panel card-glow dash-empty">{y("empty")}</div>}<div className="yt-list">{items(state.data).map(value => {
    const snippet = object(value.snippet), status = string(object(value.status).lifeCycleStatus), id = string(value.id);
    return <article className="dash-panel card-glow" key={id}><div className="dash-section-heading"><div><h3 dir="auto">{string(snippet.title)}</h3><p className="dash-help">{format.date(snippet.scheduledStartTime)}</p></div><span className="dash-tag">{y.has(status) ? y(status) : status}</span></div><div className="dash-actions"><button type="button" className="dash-button" disabled={actions.busy || !streams.length || ["live", "complete", "revoked"].includes(status)} onClick={() => setForm({ title: "bindStream", action: "liveBind", initial: { id }, fields: [{ name: "streamId", type: "select", required: true, options: streams }] })}><Link2 size={16} />{y("bindStream")}</button>{["testing", "live", "complete"].map(broadcastStatus => <button type="button" className="dash-button" key={broadcastStatus} disabled={actions.busy || broadcastStatus === "testing" && status !== "ready" || broadcastStatus === "live" && !["ready", "testing"].includes(status) || broadcastStatus === "complete" && !["live", "testing"].includes(status)} onClick={() => setForm({ title: broadcastStatus, action: "liveTransition", initial: { id, broadcastStatus }, fields: [], confirm: true })}><Radio size={15} />{y(broadcastStatus)}</button>)}<button type="button" className="dash-icon-button dash-danger" disabled={actions.busy} aria-label={y("delete")} onClick={() => setForm({ title: "deleteLive", action: "liveDelete", initial: { id }, fields: [], confirm: true })}><Trash2 size={16} /></button></div></article>;
  })}</div><YoutubePages state={state} pages={pages} />{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection>;
}
