"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { Pencil, Trash2, ImageIcon, ExternalLink, Search } from "lucide-react";
import { youtubeObject as object, youtubeString as string, youtubeItems as items, youtubeVideoId } from "@/lib/data/youtube-studio";
import { useYoutubeResource, useYoutubeActions, useYoutubeFormat, useYoutubePages, YoutubePages, YoutubeSection, YoutubeFeedback, YoutubeImage, YoutubeForm, privacyField, type StudioForm, type StudioContext } from "./youtube-ui";
import { YouTubeMediaForm } from "./YouTubeUpload";
function localDate(value: unknown) { if (typeof value !== "string" || !Number.isFinite(Date.parse(value))) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export default function YouTubeContent({ onExpired, overview = false }: StudioContext & { overview?: boolean }) {
  const y = useTranslations("youtubeStudio"), pages = useYoutubePages(), [search, setSearch] = useState("");
  const state = useYoutubeResource(overview ? "overview" : "videos", { onExpired }, { pageToken: pages.token, search });
  const actions = useYoutubeActions({ onExpired }, state.reload), format = useYoutubeFormat(), [form, setForm] = useState<StudioForm | null>(null), [thumbnail, setThumbnail] = useState("");
  const channel = object(state.data?.channel), snippet = object(channel.snippet), stats = object(channel.statistics), content = items(state.data);
  return <YoutubeSection title={overview ? "overview" : "content"} state={state}><YoutubeFeedback message={actions.message} />
    {overview && <><div className="dash-panel card-glow yt-channel-summary"><YoutubeImage snippet={snippet} /><div><h2 dir="auto">{string(snippet.title)}</h2><p className="dash-help" dir="auto">{string(snippet.description).slice(0, 400)}</p><bdi className="dash-reference">{string(channel.id)}</bdi></div></div><div className="dash-platform-metrics">{["subscriberCount", "viewCount", "videoCount"].map(key => <div className="dash-panel card-glow dash-stat" key={key}><span className="dash-help">{y(key)}</span><strong>{key === "subscriberCount" && stats.hiddenSubscriberCount ? "—" : format.number(stats[key])}</strong></div>)}</div></>}
    {!overview && <form className="yt-search hub-form" onSubmit={event => { event.preventDefault(); pages.reset(); setSearch(String(new FormData(event.currentTarget).get("search") ?? "").trim()); }}><input name="search" maxLength={100} aria-label={y("searchVideos")} placeholder={y("searchVideos")} dir="auto" /><button type="submit" className="dash-button" disabled={state.loading}><Search size={17} />{y("search")}</button></form>}
    {!content.length ? <div className="dash-panel card-glow dash-empty">{y("empty")}</div> : <div className="yt-video-grid">{content.slice(0, overview ? 6 : 25).map(value => {
      const id = youtubeVideoId(value.id), snippet = object(value.snippet), stats = object(value.statistics), status = object(value.status);
      return <article className="dash-panel card-glow yt-video" key={id}><YoutubeImage snippet={snippet} /><div className="yt-video-body"><h3 dir="auto">{string(snippet.title)}</h3><p className="dash-help"><time>{format.date(snippet.publishedAt)}</time> · {format.number(stats.viewCount)} {y("views")}</p><span className="dash-tag">{y.has(string(status.privacyStatus)) ? y(string(status.privacyStatus)) : "—"}</span><div className="dash-actions"><button type="button" className="dash-icon-button" aria-label={y("edit") + " · " + string(snippet.title)} disabled={actions.busy} onClick={() => setForm({ title: "editVideo", action: "videoUpdate", fields: [{ name: "title", required: true, max: 100 }, { name: "description", type: "textarea", max: 5000 }, { name: "tags", max: 500 }, privacyField, { name: "publishAt", type: "datetime-local" }, { name: "selfDeclaredMadeForKids", type: "checkbox" }, { name: "containsSyntheticMedia", type: "checkbox" }], initial: { id, title: snippet.title, description: snippet.description, tags: Array.isArray(snippet.tags) ? snippet.tags.join(", ") : "", privacyStatus: status.privacyStatus, publishAt: localDate(status.publishAt), selfDeclaredMadeForKids: status.selfDeclaredMadeForKids ?? status.madeForKids, containsSyntheticMedia: status.containsSyntheticMedia }, detail: y("scheduleHint") })}><Pencil size={17} /></button><button type="button" className="dash-icon-button" aria-label={y("thumbnail") + " · " + string(snippet.title)} onClick={() => setThumbnail(id)} disabled={actions.busy}><ImageIcon size={17} /></button><a className="dash-icon-button" href={"https://studio.youtube.com/video/" + id + "/edit"} target="_blank" rel="noopener noreferrer" aria-label={y("openStudio") + " · " + string(snippet.title)}><ExternalLink size={17} /></a><button type="button" className="dash-icon-button dash-danger" disabled={actions.busy} aria-label={y("delete") + " · " + string(snippet.title)} onClick={() => setForm({ title: "deleteVideo", action: "videoDelete", initial: { id }, fields: [], confirm: true, detail: string(snippet.title) })}><Trash2 size={17} /></button></div></div></article>;
    })}</div>}
    {!overview && <YoutubePages state={state} pages={pages} />}
    {form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}
    {thumbnail && <YouTubeMediaForm videoId={thumbnail} onExpired={onExpired} onClose={() => setThumbnail("")} onDone={() => void state.reload()} />}
  </YoutubeSection>;
}
