"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { Pencil, Plus, Download, Trash2, ExternalLink } from "lucide-react";
import { youtubeObject as object, youtubeString as string, youtubeItems as items, youtubeVideoId } from "@/lib/data/youtube-studio";
import { useYoutubeResource, useYoutubeActions, YoutubeSection, YoutubeFeedback, YoutubeForm, YoutubeImage, type StudioContext, type StudioForm } from "./youtube-ui";
import { YouTubeMediaForm } from "./YouTubeUpload";
export function YouTubeChannel({ onExpired }: StudioContext) {
  const y = useTranslations("youtubeStudio"), state = useYoutubeResource("channel", { onExpired }), actions = useYoutubeActions({ onExpired }, state.reload), [form, setForm] = useState<StudioForm | null>(null), channel = object(state.data?.channel), snippet = object(channel.snippet), branding = object(object(channel.brandingSettings).channel);
  return <YoutubeSection title="channel" state={state} actions={<button type="button" className="dash-button" disabled={actions.busy} onClick={() => setForm({ title: "editChannel", action: "channelUpdate", fields: [{ name: "description", type: "textarea", max: 1000 }, { name: "keywords", max: 500 }, { name: "trailer", max: 250 }], initial: { description: branding.description ?? snippet.description, keywords: branding.keywords, trailer: branding.unsubscribedTrailer } })}><Pencil size={16} />{y("editChannel")}</button>}><YoutubeFeedback message={actions.message} /><div className="dash-panel card-glow yt-channel-summary"><YoutubeImage snippet={snippet} /><div><h2 dir="auto">{string(snippet.title)}</h2><p className="yt-comment-text dash-help" dir="auto">{string(snippet.description)}</p><a className="dash-text-button" href={"https://studio.youtube.com/channel/" + string(channel.id) + "/customization"} target="_blank" rel="noopener noreferrer">{y("customization")}<ExternalLink size={15} /></a></div></div>{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection>;
}
export function YouTubeSubtitles({ onExpired }: StudioContext) {
  const y = useTranslations("youtubeStudio"), list = useYoutubeResource("videos", { onExpired }), [selected, setSelected] = useState(""), [error, setError] = useState("");
  return <section><h2>{y("subtitles")}</h2><YoutubeFeedback message={list.error || error} /><label className="yt-video-select hub-form">{y("selectVideo")}<select value={selected} onChange={e => setSelected(e.target.value)}><option value="">{y("selectVideo")}</option>{items(list.data).map(video => <option value={string(video.id)} key={string(video.id)}>{string(object(video.snippet).title)}</option>)}</select></label><p className="dash-help">{y("videoLinkHint")}</p><form className="hub-form yt-search" onSubmit={event => { event.preventDefault(); const raw = String(new FormData(event.currentTarget).get("id")); try { setSelected(youtubeVideoId(raw)); setError(""); } catch { setError("INVALID"); } }}><input name="id" maxLength={250} placeholder={y("videoLink")} aria-label={y("videoLink")} required dir="ltr" /><button className="dash-button" type="submit">{y("selectVideo")}</button></form>{selected && <CaptionList key={selected} videoId={selected} onExpired={onExpired} />}</section>;
}
function CaptionList({ videoId, onExpired }: StudioContext & { videoId: string }) {
  const y = useTranslations("youtubeStudio"), state = useYoutubeResource("captions", { onExpired }, { videoId }), actions = useYoutubeActions({ onExpired }, state.reload), [upload, setUpload] = useState(false), [form, setForm] = useState<StudioForm | null>(null);
  return <YoutubeSection title="subtitles" state={state} actions={<button type="button" className="dash-button" disabled={actions.busy} onClick={() => setUpload(true)}><Plus size={16} />{y("uploadCaption")}</button>}><YoutubeFeedback message={actions.message} /><div className="yt-list">{items(state.data).map(caption => <article className="dash-panel card-glow dash-section-heading" key={string(caption.id)}><div><h3 dir="auto">{string(object(caption.snippet).name) || string(object(caption.snippet).language)}</h3><p className="dash-help">{string(object(caption.snippet).language)} · {string(object(caption.snippet).status)}</p></div><div className="dash-actions"><a className="dash-icon-button" aria-label={y("download")} href={"/api/admin/youtube/media?" + new URLSearchParams({ videoId, id: string(caption.id) })}><Download size={16} /></a><button type="button" className="dash-icon-button dash-danger" disabled={actions.busy} aria-label={y("delete")} onClick={() => setForm({ title: "deleteCaption", action: "captionDelete", fields: [], initial: { videoId, id: caption.id }, confirm: true })}><Trash2 size={16} /></button></div></article>)}</div>{!items(state.data).length && <p className="dash-help">{y("empty")}</p>}{upload && <YouTubeMediaForm caption videoId={videoId} onExpired={onExpired} onClose={() => setUpload(false)} onDone={() => void state.reload()} />}{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection>;
}
