"use client";
import { useState } from "react";
import { useTranslations } from "next-intl";
import { MessageSquare, Check, Ban, Plus, Pencil, Trash2, ArrowLeft } from "lucide-react";
import { youtubeObject as object, youtubeString as string, youtubeItems as items } from "@/lib/data/youtube-studio";
import { useYoutubeResource, useYoutubeActions, useYoutubePages, useYoutubeFormat, YoutubeSection, YoutubeFeedback, YoutubeForm, YoutubePages, privacyField, type StudioForm, type StudioContext } from "./youtube-ui";
export function YouTubeComments({ onExpired }: StudioContext) {
  const y = useTranslations("youtubeStudio"), [filter, setFilter] = useState("published"), pages = useYoutubePages(), state = useYoutubeResource("comments", { onExpired }, { moderationStatus: filter, pageToken: pages.token });
  const actions = useYoutubeActions({ onExpired }, state.reload), [form, setForm] = useState<StudioForm | null>(null), format = useYoutubeFormat();
  return <YoutubeSection title="comments" state={state} actions={<select className="yt-range" value={filter} aria-label={y("moderationStatus")} onChange={e => { pages.reset(); setFilter(e.target.value); }}>{["published", "heldForReview", "likelySpam"].map(value => <option key={value} value={value}>{y(value)}</option>)}</select>}><YoutubeFeedback message={actions.message} />{!items(state.data).length ? <div className="dash-panel card-glow dash-empty">{y("empty")}</div> : <div className="yt-list">{items(state.data).map(thread => {
    const comment = object(object(thread.snippet).topLevelComment), snippet = object(comment.snippet), id = string(comment.id);
    return <article className="dash-panel card-glow yt-comment" key={string(thread.id)}><div className="dash-section-heading"><strong dir="auto">{string(snippet.authorDisplayName)}</strong><span className="dash-help">{format.date(snippet.publishedAt)}</span></div><p className="yt-comment-text" dir="auto">{string(snippet.textOriginal ?? snippet.textDisplay)}</p><div className="dash-actions"><button className="dash-button" type="button" disabled={actions.busy || object(thread.snippet).canReply === false} onClick={() => setForm({ title: "reply", action: "commentReply", fields: [{ name: "text", label: "replyText", type: "textarea", required: true, max: 10000 }], initial: { id }, confirm: true, detail: string(snippet.textOriginal ?? snippet.textDisplay).slice(0, 500) })}><MessageSquare size={15} />{y("reply")}</button>{["published", "heldForReview", "rejected"].map(moderationStatus => <button className="dash-icon-button" key={moderationStatus} aria-label={y(moderationStatus)} disabled={actions.busy} type="button" onClick={() => setForm({ title: moderationStatus, action: "commentModerate", fields: [], initial: { id, moderationStatus }, confirm: true })}>{moderationStatus === "published" ? <Check size={17} /> : moderationStatus === "rejected" ? <Ban size={17} /> : <MessageSquare size={17} />}</button>)}</div>{items({ items: object(thread.replies).comments }).map(reply => <div className="yt-reply" key={string(reply.id)}><strong dir="auto">{string(object(reply.snippet).authorDisplayName)}</strong><p dir="auto">{string(object(reply.snippet).textOriginal ?? object(reply.snippet).textDisplay)}</p></div>)}</article>;
  })}</div>}<YoutubePages state={state} pages={pages} />{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection>;
}
const playlistFields: StudioForm["fields"] = [{ name: "title", required: true, max: 150 }, { name: "description", type: "textarea", max: 5000 }, privacyField];
export function YouTubePlaylists({ onExpired }: StudioContext) {
  const y = useTranslations("youtubeStudio"), pages = useYoutubePages(), state = useYoutubeResource("playlists", { onExpired }, { pageToken: pages.token }), actions = useYoutubeActions({ onExpired }, state.reload), [form, setForm] = useState<StudioForm | null>(null), [selected, setSelected] = useState<Record<string, unknown> | null>(null), format = useYoutubeFormat();
  if (selected) return <YouTubePlaylistItems playlist={selected} onExpired={onExpired} onBack={() => { setSelected(null); void state.reload(); }} />;
  return <YoutubeSection title="playlists" state={state} actions={<button type="button" className="dash-button dash-button-primary" disabled={actions.busy} onClick={() => setForm({ title: "createPlaylist", action: "playlistCreate", fields: playlistFields, initial: { privacyStatus: "private" } })}><Plus size={16} />{y("createPlaylist")}</button>}><YoutubeFeedback message={actions.message} /><div className="yt-list">{items(state.data).map(value => <article className="dash-panel card-glow" key={string(value.id)}><div className="dash-section-heading"><div><h3 dir="auto">{string(object(value.snippet).title)}</h3><p className="dash-help">{format.number(object(value.contentDetails).itemCount)} {y("videos")}</p></div><div className="dash-actions"><button type="button" className="dash-button" onClick={() => setSelected(value)}>{y("manage")}</button><button type="button" className="dash-icon-button" disabled={actions.busy} aria-label={y("edit")} onClick={() => setForm({ title: "editPlaylist", action: "playlistUpdate", fields: playlistFields, initial: { id: value.id, title: object(value.snippet).title, description: object(value.snippet).description, privacyStatus: object(value.status).privacyStatus } })}><Pencil size={16} /></button><button type="button" className="dash-icon-button dash-danger" disabled={actions.busy} aria-label={y("delete")} onClick={() => setForm({ title: "deletePlaylist", action: "playlistDelete", fields: [], initial: { id: value.id }, confirm: true })}><Trash2 size={16} /></button></div></div></article>)}</div>{!items(state.data).length && <p className="dash-help">{y("empty")}</p>}<YoutubePages state={state} pages={pages} />{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection>;
}
function YouTubePlaylistItems({ playlist, onExpired, onBack }: StudioContext & { playlist: Record<string, unknown>; onBack: () => void }) {
  const y = useTranslations("youtubeStudio"), pages = useYoutubePages(), state = useYoutubeResource("playlistItems", { onExpired }, { id: string(playlist.id), pageToken: pages.token }), actions = useYoutubeActions({ onExpired }, state.reload), [form, setForm] = useState<StudioForm | null>(null);
  return <><button type="button" className="dash-text-button" onClick={onBack}><ArrowLeft size={16} />{y("playlists")}</button><h2 dir="auto">{string(object(playlist.snippet).title)}</h2><YoutubeSection title="content" state={state} actions={<button type="button" className="dash-button" disabled={actions.busy} onClick={() => setForm({ title: "addVideo", action: "playlistAdd", fields: [{ name: "videoId", label: "videoLink", required: true, max: 250 }], initial: { id: playlist.id } })}><Plus size={16} />{y("addVideo")}</button>}><YoutubeFeedback message={actions.message} /><div className="yt-list">{items(state.data).map(item => <article className="dash-panel card-glow dash-section-heading" key={string(item.id)}><h3 dir="auto">{string(object(item.snippet).title)}</h3><button type="button" className="dash-icon-button dash-danger" disabled={actions.busy} aria-label={y("delete")} onClick={() => setForm({ title: "removeVideo", action: "playlistRemove", fields: [], initial: { itemId: item.id }, confirm: true })}><Trash2 size={16} /></button></article>)}</div><YoutubePages state={state} pages={pages} />{form && <YoutubeForm form={form} busy={actions.busy} run={actions.run} onClose={() => setForm(null)} />}</YoutubeSection></>;
}
