import fs from 'node:fs';
import * as THREE from 'three';
import {OBJLoader} from 'three/examples/jsm/loaders/OBJLoader.js';
import {GLTFExporter} from 'three/examples/jsm/exporters/GLTFExporter.js';
import {mergeVertices} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
globalThis.FileReader=class {readAsArrayBuffer(blob){blob.arrayBuffer().then(b=>{this.result=b;this.onloadend?.();});}};
if(!process.argv[2])throw Error('Pass the extracted Cartoon Space Pack directory');
const source=process.argv[2]+'/';
const output=new URL('../public/assets/models/rocket-v101/',import.meta.url);
fs.mkdirSync(output,{recursive:true});
const scene=new OBJLoader().parse(fs.readFileSync(source+'a150c4f658974b74a667e9933c792dfe.obj','utf8'));
const rocket=scene.children.find(m=>m.name==='Rocket_Rocket_0');
if(!rocket)throw Error('Rocket mesh missing');
rocket.geometry=mergeVertices(rocket.geometry,0.00001);rocket.geometry.center();
rocket.material=new THREE.MeshStandardMaterial();
const binary=await new GLTFExporter().parseAsync(rocket,{binary:true});
fs.writeFileSync(new URL('Rocket.glb',output),Buffer.from(binary));
for(const f of fs.readdirSync(source).filter(f=>/_Rocket_(BaseColor|Normal|Roughtness)\.png$/.test(f)))fs.copyFileSync(source+f,new URL(f,output));
console.log(rocket.name,new THREE.Box3().setFromObject(rocket).getSize(new THREE.Vector3()));
