"use client";
import Link from "next/link";
import { useCallback,useState } from "react";
import QueryObserver from "./QueryObserver";
import { useTranslations } from "next-intl";
import FaqAccordion,{type FaqItem} from "@/components/faq/FaqAccordion";
import ContentFeed from "./ContentFeed";
import Receipt from "./Receipt";
import { saveReceipt } from "@/lib/data/hub-receipts";
import { DISCORD_LINK } from "@/lib/data/site";
export default function SupportCenter() {
  const t=useTranslations("hub"),faq=useTranslations("faq"),common=useTranslations("common"),creator=useTranslations("creators");
  const [tab,setTab]=useState("faq"),[order,setOrder]=useState(""),[type,setType]=useState("technical"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState<{reference:string;token:string}|null>(null);
  const queryChanged=useCallback((value:string|null)=>{if(value){setOrder(value.slice(0,128));setType("order");setTab("report");}},[]);
  return <><QueryObserver param="order" onChange={queryChanged}/><div className="hub-actions mb-8" role="group" aria-label={t("support")}>{["faq","rules","report"].map(value=><button key={value} type="button" className="hub-button" aria-pressed={tab===value} onClick={()=>setTab(value)}>{value==="faq"?faq("title"):t(value)}</button>)}<Link href="/minecraft#common-errors" className="hub-button">{t("commonErrorsTitle")}</Link><Link href="/requests?tab=support" className="hub-button">{t("track")}</Link><a href={DISCORD_LINK} className="hub-button" target="_blank" rel="noopener noreferrer">Discord</a></div>{tab==="faq"?<div id="faq"><FaqAccordion items={faq.raw("items") as FaqItem[]} categories={faq.raw("categories") as Record<string,string>} searchPlaceholder={faq("searchPlaceholder")} noResults={faq("noResults")} allLabel={common("all")}/></div>:tab==="rules"?<ContentFeed kind="rule"/>:<div className="hub-card max-w-[760px]">{receipt?<Receipt kind="support" {...receipt}/>:<form className="hub-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const data=new FormData(e.currentTarget);setBusy(true);setError("");try{const response=await fetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),consent:data.get("consent")==="on"})});const result=await response.json();if(!response.ok)throw Error(result.error);saveReceipt("support",result);setReceipt(result);}catch(e){setError(e instanceof Error&&e.message==="RATE_LIMIT"?"rateLimit":"unavailable");}finally{setBusy(false);}}}><label>{t("reportType")}<select name="type" value={type} onChange={e=>setType(e.target.value)}>{["technical","player","order"].map(value=><option key={value} value={value}>{t("report_"+value)}</option>)}</select></label><label>{creator("email")}<input name="email" type="email" required maxLength={254}/></label><label>{creator("minecraft")}<input name="username" dir="ltr" maxLength={32}/></label><label>{t("orderReference")}<input name="order" dir="ltr" value={order} onChange={e=>setOrder(e.target.value)} maxLength={128}/></label><label>{t("subject")}<input name="subject" required minLength={3} maxLength={160}/></label><label>{t("message")}<textarea name="message" required minLength={20} maxLength={3000} rows={6}/></label><label className="hub-honey" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="hub-consent"><input type="checkbox" name="consent" required/>{t("consent")}</label><p className="hub-muted">{t("webhookNote")}</p>{error&&<p role="alert" className="hub-error">{t(error)}</p>}<button className="hub-button" disabled={busy}>{t(busy?"sending":"send")}</button></form>}</div>}</>;
}
