"use client";
import Link from "next/link";
import { useEffect,useState,type FormEvent } from "react";
import { useTranslations,useLocale } from "next-intl";
import { RECEIPT_KEY,parseReceipts,type SavedReceipt,type ReceiptKind } from "@/lib/data/hub-receipts";
type Result = { reference:string;status:string;note?:string;delivery?:string;username?:string;createdAt:string;platform?:string;eventTitle?:string; };
export default function TrackingPanel({kind}:{kind:ReceiptKind}) {
  const t=useTranslations("hub"),locale=useLocale();
  const [receipts,setReceipts]=useState<SavedReceipt[]>([]),[reference,setReference]=useState(""),[token,setToken]=useState(""),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{const load=()=>{try{setReceipts(parseReceipts(localStorage.getItem(RECEIPT_KEY)).filter(row=>row.kind===kind));}catch{}};queueMicrotask(load);window.addEventListener("storage",load);window.addEventListener("zo7al-receipts",load);return()=>{window.removeEventListener("storage",load);window.removeEventListener("zo7al-receipts",load);};},[kind]);
  async function track(r=reference,c=token) {
    if(busy)return;setBusy(true);setError("");setResult(null);
    try{const response=await fetch("/api/tracking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,reference:r.trim(),token:c.trim()})});const data=await response.json();if(!response.ok)throw Error(response.status===404?"notFound":response.status===429?"rateLimit":"unavailable");setResult(data);}catch(e){setError(e instanceof Error&&["notFound","rateLimit"].includes(e.message)?e.message:"unavailable");}finally{setBusy(false);}
  }
  return <div className="hub-grid"><div className="hub-card"><h2 className="text-display text-2xl mb-4">{t("track")}</h2><p className="hub-muted mb-5">{t("trackingHelp")}</p><form className="hub-form" onSubmit={(e:FormEvent)=>{e.preventDefault();void track();}}><label>{t("reference")}<input dir="ltr" required value={reference} onChange={e=>setReference(e.target.value)} minLength={36} maxLength={36}/></label><label>{t("accessCode")}<input type="password" dir="ltr" required value={token} onChange={e=>setToken(e.target.value)} minLength={64} maxLength={64} autoComplete="off"/></label><button className="hub-button" disabled={busy}>{t(busy?"loading":"track")}</button></form>{error&&<p role="alert" className="hub-error mt-4">{t(error)}</p>}</div><div><h2 className="mb-4 text-lg font-semibold">{t("savedRequests")}</h2>{receipts.length?<div className="space-y-3">{receipts.map(receipt=><button key={receipt.reference} className="hub-card w-full text-start" type="button" disabled={busy} onClick={()=>{setReference(receipt.reference);setToken(receipt.token);void track(receipt.reference,receipt.token);}}><bdi className="block break-all text-xs">{receipt.reference}</bdi><time className="hub-muted">{new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(receipt.savedAt))}</time></button>)}</div>:<p className="hub-muted">{t("noSavedRequests")}</p>}</div>{result&&<article className="hub-card"><h2 className="text-lg font-semibold">{result.eventTitle??result.username??result.platform??t("status")}</h2><span className="hub-status">{t.has("status_"+result.status)?t("status_"+result.status):t("status_unknown")}</span>{kind==="order"&&<><p className="hub-muted">{t("paymentDeliveryNote")}</p><p>{t("delivery")}: {t.has("delivery_"+result.delivery)?t("delivery_"+result.delivery):t("delivery_unknown")}</p><div className="hub-actions"><Link href={"/minecraft?order="+encodeURIComponent(result.reference)+"#support"} className="hub-button">{t("orderSupport")}</Link><a href="https://portal.tebex.io/" className="hub-button" target="_blank" rel="noopener noreferrer">{t("subscriptions")}</a></div></>}{result.note&&<p dir="auto" className="whitespace-pre-line">{result.note}</p>}<p className="hub-muted"><time>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(result.createdAt))}</time></p></article>}</div>;
}
